package com.jupiter.ts.model;

public class Annunciator {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_xh.id
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_xh.xh_name
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    private String xhName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_xh.xh_create
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    private Long xhCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_xh.xh_modified
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    private Long xhModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_xh.id
     *
     * @return the value of ts_xh.id
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_xh.id
     *
     * @param id the value for ts_xh.id
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_xh.xh_name
     *
     * @return the value of ts_xh.xh_name
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public String getXhName() {
        return xhName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_xh.xh_name
     *
     * @param xhName the value for ts_xh.xh_name
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void setXhName(String xhName) {
        this.xhName = xhName == null ? null : xhName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_xh.xh_create
     *
     * @return the value of ts_xh.xh_create
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public Long getXhCreate() {
        return xhCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_xh.xh_create
     *
     * @param xhCreate the value for ts_xh.xh_create
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void setXhCreate(Long xhCreate) {
        this.xhCreate = xhCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_xh.xh_modified
     *
     * @return the value of ts_xh.xh_modified
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public Long getXhModified() {
        return xhModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_xh.xh_modified
     *
     * @param xhModified the value for ts_xh.xh_modified
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void setXhModified(Long xhModified) {
        this.xhModified = xhModified;
    }
}