package com.jupiter.ts.model;

import java.util.ArrayList;
import java.util.List;

public class AnnunciatorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ts_xh
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ts_xh
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ts_xh
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_xh
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    public AnnunciatorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_xh
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_xh
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_xh
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_xh
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_xh
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_xh
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_xh
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_xh
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_xh
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_xh
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ts_xh
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andXhNameIsNull() {
            addCriterion("xh_name is null");
            return (Criteria) this;
        }

        public Criteria andXhNameIsNotNull() {
            addCriterion("xh_name is not null");
            return (Criteria) this;
        }

        public Criteria andXhNameEqualTo(String value) {
            addCriterion("xh_name =", value, "xhName");
            return (Criteria) this;
        }

        public Criteria andXhNameNotEqualTo(String value) {
            addCriterion("xh_name <>", value, "xhName");
            return (Criteria) this;
        }

        public Criteria andXhNameGreaterThan(String value) {
            addCriterion("xh_name >", value, "xhName");
            return (Criteria) this;
        }

        public Criteria andXhNameGreaterThanOrEqualTo(String value) {
            addCriterion("xh_name >=", value, "xhName");
            return (Criteria) this;
        }

        public Criteria andXhNameLessThan(String value) {
            addCriterion("xh_name <", value, "xhName");
            return (Criteria) this;
        }

        public Criteria andXhNameLessThanOrEqualTo(String value) {
            addCriterion("xh_name <=", value, "xhName");
            return (Criteria) this;
        }

        public Criteria andXhNameLike(String value) {
            addCriterion("xh_name like", value, "xhName");
            return (Criteria) this;
        }

        public Criteria andXhNameNotLike(String value) {
            addCriterion("xh_name not like", value, "xhName");
            return (Criteria) this;
        }

        public Criteria andXhNameIn(List<String> values) {
            addCriterion("xh_name in", values, "xhName");
            return (Criteria) this;
        }

        public Criteria andXhNameNotIn(List<String> values) {
            addCriterion("xh_name not in", values, "xhName");
            return (Criteria) this;
        }

        public Criteria andXhNameBetween(String value1, String value2) {
            addCriterion("xh_name between", value1, value2, "xhName");
            return (Criteria) this;
        }

        public Criteria andXhNameNotBetween(String value1, String value2) {
            addCriterion("xh_name not between", value1, value2, "xhName");
            return (Criteria) this;
        }

        public Criteria andXhCreateIsNull() {
            addCriterion("xh_create is null");
            return (Criteria) this;
        }

        public Criteria andXhCreateIsNotNull() {
            addCriterion("xh_create is not null");
            return (Criteria) this;
        }

        public Criteria andXhCreateEqualTo(Long value) {
            addCriterion("xh_create =", value, "xhCreate");
            return (Criteria) this;
        }

        public Criteria andXhCreateNotEqualTo(Long value) {
            addCriterion("xh_create <>", value, "xhCreate");
            return (Criteria) this;
        }

        public Criteria andXhCreateGreaterThan(Long value) {
            addCriterion("xh_create >", value, "xhCreate");
            return (Criteria) this;
        }

        public Criteria andXhCreateGreaterThanOrEqualTo(Long value) {
            addCriterion("xh_create >=", value, "xhCreate");
            return (Criteria) this;
        }

        public Criteria andXhCreateLessThan(Long value) {
            addCriterion("xh_create <", value, "xhCreate");
            return (Criteria) this;
        }

        public Criteria andXhCreateLessThanOrEqualTo(Long value) {
            addCriterion("xh_create <=", value, "xhCreate");
            return (Criteria) this;
        }

        public Criteria andXhCreateIn(List<Long> values) {
            addCriterion("xh_create in", values, "xhCreate");
            return (Criteria) this;
        }

        public Criteria andXhCreateNotIn(List<Long> values) {
            addCriterion("xh_create not in", values, "xhCreate");
            return (Criteria) this;
        }

        public Criteria andXhCreateBetween(Long value1, Long value2) {
            addCriterion("xh_create between", value1, value2, "xhCreate");
            return (Criteria) this;
        }

        public Criteria andXhCreateNotBetween(Long value1, Long value2) {
            addCriterion("xh_create not between", value1, value2, "xhCreate");
            return (Criteria) this;
        }

        public Criteria andXhModifiedIsNull() {
            addCriterion("xh_modified is null");
            return (Criteria) this;
        }

        public Criteria andXhModifiedIsNotNull() {
            addCriterion("xh_modified is not null");
            return (Criteria) this;
        }

        public Criteria andXhModifiedEqualTo(Long value) {
            addCriterion("xh_modified =", value, "xhModified");
            return (Criteria) this;
        }

        public Criteria andXhModifiedNotEqualTo(Long value) {
            addCriterion("xh_modified <>", value, "xhModified");
            return (Criteria) this;
        }

        public Criteria andXhModifiedGreaterThan(Long value) {
            addCriterion("xh_modified >", value, "xhModified");
            return (Criteria) this;
        }

        public Criteria andXhModifiedGreaterThanOrEqualTo(Long value) {
            addCriterion("xh_modified >=", value, "xhModified");
            return (Criteria) this;
        }

        public Criteria andXhModifiedLessThan(Long value) {
            addCriterion("xh_modified <", value, "xhModified");
            return (Criteria) this;
        }

        public Criteria andXhModifiedLessThanOrEqualTo(Long value) {
            addCriterion("xh_modified <=", value, "xhModified");
            return (Criteria) this;
        }

        public Criteria andXhModifiedIn(List<Long> values) {
            addCriterion("xh_modified in", values, "xhModified");
            return (Criteria) this;
        }

        public Criteria andXhModifiedNotIn(List<Long> values) {
            addCriterion("xh_modified not in", values, "xhModified");
            return (Criteria) this;
        }

        public Criteria andXhModifiedBetween(Long value1, Long value2) {
            addCriterion("xh_modified between", value1, value2, "xhModified");
            return (Criteria) this;
        }

        public Criteria andXhModifiedNotBetween(Long value1, Long value2) {
            addCriterion("xh_modified not between", value1, value2, "xhModified");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ts_xh
     *
     * @mbg.generated do_not_delete_during_merge Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ts_xh
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}