package com.jupiter.ts.model;

import java.util.ArrayList;
import java.util.List;

public class BrigadeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ts_dd
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ts_dd
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ts_dd
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dd
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public BrigadeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dd
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dd
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dd
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dd
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dd
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dd
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dd
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dd
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dd
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dd
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ts_dd
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDdNameIsNull() {
            addCriterion("dd_name is null");
            return (Criteria) this;
        }

        public Criteria andDdNameIsNotNull() {
            addCriterion("dd_name is not null");
            return (Criteria) this;
        }

        public Criteria andDdNameEqualTo(String value) {
            addCriterion("dd_name =", value, "ddName");
            return (Criteria) this;
        }

        public Criteria andDdNameNotEqualTo(String value) {
            addCriterion("dd_name <>", value, "ddName");
            return (Criteria) this;
        }

        public Criteria andDdNameGreaterThan(String value) {
            addCriterion("dd_name >", value, "ddName");
            return (Criteria) this;
        }

        public Criteria andDdNameGreaterThanOrEqualTo(String value) {
            addCriterion("dd_name >=", value, "ddName");
            return (Criteria) this;
        }

        public Criteria andDdNameLessThan(String value) {
            addCriterion("dd_name <", value, "ddName");
            return (Criteria) this;
        }

        public Criteria andDdNameLessThanOrEqualTo(String value) {
            addCriterion("dd_name <=", value, "ddName");
            return (Criteria) this;
        }

        public Criteria andDdNameLike(String value) {
            addCriterion("dd_name like", value, "ddName");
            return (Criteria) this;
        }

        public Criteria andDdNameNotLike(String value) {
            addCriterion("dd_name not like", value, "ddName");
            return (Criteria) this;
        }

        public Criteria andDdNameIn(List<String> values) {
            addCriterion("dd_name in", values, "ddName");
            return (Criteria) this;
        }

        public Criteria andDdNameNotIn(List<String> values) {
            addCriterion("dd_name not in", values, "ddName");
            return (Criteria) this;
        }

        public Criteria andDdNameBetween(String value1, String value2) {
            addCriterion("dd_name between", value1, value2, "ddName");
            return (Criteria) this;
        }

        public Criteria andDdNameNotBetween(String value1, String value2) {
            addCriterion("dd_name not between", value1, value2, "ddName");
            return (Criteria) this;
        }

        public Criteria andDdCreateIsNull() {
            addCriterion("dd_create is null");
            return (Criteria) this;
        }

        public Criteria andDdCreateIsNotNull() {
            addCriterion("dd_create is not null");
            return (Criteria) this;
        }

        public Criteria andDdCreateEqualTo(Long value) {
            addCriterion("dd_create =", value, "ddCreate");
            return (Criteria) this;
        }

        public Criteria andDdCreateNotEqualTo(Long value) {
            addCriterion("dd_create <>", value, "ddCreate");
            return (Criteria) this;
        }

        public Criteria andDdCreateGreaterThan(Long value) {
            addCriterion("dd_create >", value, "ddCreate");
            return (Criteria) this;
        }

        public Criteria andDdCreateGreaterThanOrEqualTo(Long value) {
            addCriterion("dd_create >=", value, "ddCreate");
            return (Criteria) this;
        }

        public Criteria andDdCreateLessThan(Long value) {
            addCriterion("dd_create <", value, "ddCreate");
            return (Criteria) this;
        }

        public Criteria andDdCreateLessThanOrEqualTo(Long value) {
            addCriterion("dd_create <=", value, "ddCreate");
            return (Criteria) this;
        }

        public Criteria andDdCreateIn(List<Long> values) {
            addCriterion("dd_create in", values, "ddCreate");
            return (Criteria) this;
        }

        public Criteria andDdCreateNotIn(List<Long> values) {
            addCriterion("dd_create not in", values, "ddCreate");
            return (Criteria) this;
        }

        public Criteria andDdCreateBetween(Long value1, Long value2) {
            addCriterion("dd_create between", value1, value2, "ddCreate");
            return (Criteria) this;
        }

        public Criteria andDdCreateNotBetween(Long value1, Long value2) {
            addCriterion("dd_create not between", value1, value2, "ddCreate");
            return (Criteria) this;
        }

        public Criteria andDdModifiedIsNull() {
            addCriterion("dd_modified is null");
            return (Criteria) this;
        }

        public Criteria andDdModifiedIsNotNull() {
            addCriterion("dd_modified is not null");
            return (Criteria) this;
        }

        public Criteria andDdModifiedEqualTo(Long value) {
            addCriterion("dd_modified =", value, "ddModified");
            return (Criteria) this;
        }

        public Criteria andDdModifiedNotEqualTo(Long value) {
            addCriterion("dd_modified <>", value, "ddModified");
            return (Criteria) this;
        }

        public Criteria andDdModifiedGreaterThan(Long value) {
            addCriterion("dd_modified >", value, "ddModified");
            return (Criteria) this;
        }

        public Criteria andDdModifiedGreaterThanOrEqualTo(Long value) {
            addCriterion("dd_modified >=", value, "ddModified");
            return (Criteria) this;
        }

        public Criteria andDdModifiedLessThan(Long value) {
            addCriterion("dd_modified <", value, "ddModified");
            return (Criteria) this;
        }

        public Criteria andDdModifiedLessThanOrEqualTo(Long value) {
            addCriterion("dd_modified <=", value, "ddModified");
            return (Criteria) this;
        }

        public Criteria andDdModifiedIn(List<Long> values) {
            addCriterion("dd_modified in", values, "ddModified");
            return (Criteria) this;
        }

        public Criteria andDdModifiedNotIn(List<Long> values) {
            addCriterion("dd_modified not in", values, "ddModified");
            return (Criteria) this;
        }

        public Criteria andDdModifiedBetween(Long value1, Long value2) {
            addCriterion("dd_modified between", value1, value2, "ddModified");
            return (Criteria) this;
        }

        public Criteria andDdModifiedNotBetween(Long value1, Long value2) {
            addCriterion("dd_modified not between", value1, value2, "ddModified");
            return (Criteria) this;
        }

        public Criteria andDdRespIsNull() {
            addCriterion("dd_resp is null");
            return (Criteria) this;
        }

        public Criteria andDdRespIsNotNull() {
            addCriterion("dd_resp is not null");
            return (Criteria) this;
        }

        public Criteria andDdRespEqualTo(String value) {
            addCriterion("dd_resp =", value, "ddResp");
            return (Criteria) this;
        }

        public Criteria andDdRespNotEqualTo(String value) {
            addCriterion("dd_resp <>", value, "ddResp");
            return (Criteria) this;
        }

        public Criteria andDdRespGreaterThan(String value) {
            addCriterion("dd_resp >", value, "ddResp");
            return (Criteria) this;
        }

        public Criteria andDdRespGreaterThanOrEqualTo(String value) {
            addCriterion("dd_resp >=", value, "ddResp");
            return (Criteria) this;
        }

        public Criteria andDdRespLessThan(String value) {
            addCriterion("dd_resp <", value, "ddResp");
            return (Criteria) this;
        }

        public Criteria andDdRespLessThanOrEqualTo(String value) {
            addCriterion("dd_resp <=", value, "ddResp");
            return (Criteria) this;
        }

        public Criteria andDdRespLike(String value) {
            addCriterion("dd_resp like", value, "ddResp");
            return (Criteria) this;
        }

        public Criteria andDdRespNotLike(String value) {
            addCriterion("dd_resp not like", value, "ddResp");
            return (Criteria) this;
        }

        public Criteria andDdRespIn(List<String> values) {
            addCriterion("dd_resp in", values, "ddResp");
            return (Criteria) this;
        }

        public Criteria andDdRespNotIn(List<String> values) {
            addCriterion("dd_resp not in", values, "ddResp");
            return (Criteria) this;
        }

        public Criteria andDdRespBetween(String value1, String value2) {
            addCriterion("dd_resp between", value1, value2, "ddResp");
            return (Criteria) this;
        }

        public Criteria andDdRespNotBetween(String value1, String value2) {
            addCriterion("dd_resp not between", value1, value2, "ddResp");
            return (Criteria) this;
        }

        public Criteria andDdRespPhoneIsNull() {
            addCriterion("dd_resp_phone is null");
            return (Criteria) this;
        }

        public Criteria andDdRespPhoneIsNotNull() {
            addCriterion("dd_resp_phone is not null");
            return (Criteria) this;
        }

        public Criteria andDdRespPhoneEqualTo(String value) {
            addCriterion("dd_resp_phone =", value, "ddRespPhone");
            return (Criteria) this;
        }

        public Criteria andDdRespPhoneNotEqualTo(String value) {
            addCriterion("dd_resp_phone <>", value, "ddRespPhone");
            return (Criteria) this;
        }

        public Criteria andDdRespPhoneGreaterThan(String value) {
            addCriterion("dd_resp_phone >", value, "ddRespPhone");
            return (Criteria) this;
        }

        public Criteria andDdRespPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("dd_resp_phone >=", value, "ddRespPhone");
            return (Criteria) this;
        }

        public Criteria andDdRespPhoneLessThan(String value) {
            addCriterion("dd_resp_phone <", value, "ddRespPhone");
            return (Criteria) this;
        }

        public Criteria andDdRespPhoneLessThanOrEqualTo(String value) {
            addCriterion("dd_resp_phone <=", value, "ddRespPhone");
            return (Criteria) this;
        }

        public Criteria andDdRespPhoneLike(String value) {
            addCriterion("dd_resp_phone like", value, "ddRespPhone");
            return (Criteria) this;
        }

        public Criteria andDdRespPhoneNotLike(String value) {
            addCriterion("dd_resp_phone not like", value, "ddRespPhone");
            return (Criteria) this;
        }

        public Criteria andDdRespPhoneIn(List<String> values) {
            addCriterion("dd_resp_phone in", values, "ddRespPhone");
            return (Criteria) this;
        }

        public Criteria andDdRespPhoneNotIn(List<String> values) {
            addCriterion("dd_resp_phone not in", values, "ddRespPhone");
            return (Criteria) this;
        }

        public Criteria andDdRespPhoneBetween(String value1, String value2) {
            addCriterion("dd_resp_phone between", value1, value2, "ddRespPhone");
            return (Criteria) this;
        }

        public Criteria andDdRespPhoneNotBetween(String value1, String value2) {
            addCriterion("dd_resp_phone not between", value1, value2, "ddRespPhone");
            return (Criteria) this;
        }

        public Criteria andDdRespAddressIsNull() {
            addCriterion("dd_resp_address is null");
            return (Criteria) this;
        }

        public Criteria andDdRespAddressIsNotNull() {
            addCriterion("dd_resp_address is not null");
            return (Criteria) this;
        }

        public Criteria andDdRespAddressEqualTo(String value) {
            addCriterion("dd_resp_address =", value, "ddRespAddress");
            return (Criteria) this;
        }

        public Criteria andDdRespAddressNotEqualTo(String value) {
            addCriterion("dd_resp_address <>", value, "ddRespAddress");
            return (Criteria) this;
        }

        public Criteria andDdRespAddressGreaterThan(String value) {
            addCriterion("dd_resp_address >", value, "ddRespAddress");
            return (Criteria) this;
        }

        public Criteria andDdRespAddressGreaterThanOrEqualTo(String value) {
            addCriterion("dd_resp_address >=", value, "ddRespAddress");
            return (Criteria) this;
        }

        public Criteria andDdRespAddressLessThan(String value) {
            addCriterion("dd_resp_address <", value, "ddRespAddress");
            return (Criteria) this;
        }

        public Criteria andDdRespAddressLessThanOrEqualTo(String value) {
            addCriterion("dd_resp_address <=", value, "ddRespAddress");
            return (Criteria) this;
        }

        public Criteria andDdRespAddressLike(String value) {
            addCriterion("dd_resp_address like", value, "ddRespAddress");
            return (Criteria) this;
        }

        public Criteria andDdRespAddressNotLike(String value) {
            addCriterion("dd_resp_address not like", value, "ddRespAddress");
            return (Criteria) this;
        }

        public Criteria andDdRespAddressIn(List<String> values) {
            addCriterion("dd_resp_address in", values, "ddRespAddress");
            return (Criteria) this;
        }

        public Criteria andDdRespAddressNotIn(List<String> values) {
            addCriterion("dd_resp_address not in", values, "ddRespAddress");
            return (Criteria) this;
        }

        public Criteria andDdRespAddressBetween(String value1, String value2) {
            addCriterion("dd_resp_address between", value1, value2, "ddRespAddress");
            return (Criteria) this;
        }

        public Criteria andDdRespAddressNotBetween(String value1, String value2) {
            addCriterion("dd_resp_address not between", value1, value2, "ddRespAddress");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ts_dd
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ts_dd
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}