package com.jupiter.ts.model;

public class Brigade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_dd.id
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_dd.dd_name
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    private String ddName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_dd.dd_create
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    private Long ddCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_dd.dd_modified
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    private Long ddModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_dd.dd_resp
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    private String ddResp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_dd.dd_resp_phone
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    private String ddRespPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_dd.dd_resp_address
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    private String ddRespAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_dd.id
     *
     * @return the value of ts_dd.id
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_dd.id
     *
     * @param id the value for ts_dd.id
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_dd.dd_name
     *
     * @return the value of ts_dd.dd_name
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public String getDdName() {
        return ddName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_dd.dd_name
     *
     * @param ddName the value for ts_dd.dd_name
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public void setDdName(String ddName) {
        this.ddName = ddName == null ? null : ddName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_dd.dd_create
     *
     * @return the value of ts_dd.dd_create
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public Long getDdCreate() {
        return ddCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_dd.dd_create
     *
     * @param ddCreate the value for ts_dd.dd_create
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public void setDdCreate(Long ddCreate) {
        this.ddCreate = ddCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_dd.dd_modified
     *
     * @return the value of ts_dd.dd_modified
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public Long getDdModified() {
        return ddModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_dd.dd_modified
     *
     * @param ddModified the value for ts_dd.dd_modified
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public void setDdModified(Long ddModified) {
        this.ddModified = ddModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_dd.dd_resp
     *
     * @return the value of ts_dd.dd_resp
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public String getDdResp() {
        return ddResp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_dd.dd_resp
     *
     * @param ddResp the value for ts_dd.dd_resp
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public void setDdResp(String ddResp) {
        this.ddResp = ddResp == null ? null : ddResp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_dd.dd_resp_phone
     *
     * @return the value of ts_dd.dd_resp_phone
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public String getDdRespPhone() {
        return ddRespPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_dd.dd_resp_phone
     *
     * @param ddRespPhone the value for ts_dd.dd_resp_phone
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public void setDdRespPhone(String ddRespPhone) {
        this.ddRespPhone = ddRespPhone == null ? null : ddRespPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_dd.dd_resp_address
     *
     * @return the value of ts_dd.dd_resp_address
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public String getDdRespAddress() {
        return ddRespAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_dd.dd_resp_address
     *
     * @param ddRespAddress the value for ts_dd.dd_resp_address
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public void setDdRespAddress(String ddRespAddress) {
        this.ddRespAddress = ddRespAddress == null ? null : ddRespAddress.trim();
    }
}