package com.jupiter.ts.model;

import java.util.ArrayList;
import java.util.List;

public class IntersectionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ts_is
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ts_is
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ts_is
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_is
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public IntersectionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_is
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_is
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_is
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_is
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_is
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_is
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_is
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_is
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_is
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_is
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ts_is
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIsNameIsNull() {
            addCriterion("is_name is null");
            return (Criteria) this;
        }

        public Criteria andIsNameIsNotNull() {
            addCriterion("is_name is not null");
            return (Criteria) this;
        }

        public Criteria andIsNameEqualTo(String value) {
            addCriterion("is_name =", value, "isName");
            return (Criteria) this;
        }

        public Criteria andIsNameNotEqualTo(String value) {
            addCriterion("is_name <>", value, "isName");
            return (Criteria) this;
        }

        public Criteria andIsNameGreaterThan(String value) {
            addCriterion("is_name >", value, "isName");
            return (Criteria) this;
        }

        public Criteria andIsNameGreaterThanOrEqualTo(String value) {
            addCriterion("is_name >=", value, "isName");
            return (Criteria) this;
        }

        public Criteria andIsNameLessThan(String value) {
            addCriterion("is_name <", value, "isName");
            return (Criteria) this;
        }

        public Criteria andIsNameLessThanOrEqualTo(String value) {
            addCriterion("is_name <=", value, "isName");
            return (Criteria) this;
        }

        public Criteria andIsNameLike(String value) {
            addCriterion("is_name like", value, "isName");
            return (Criteria) this;
        }

        public Criteria andIsNameNotLike(String value) {
            addCriterion("is_name not like", value, "isName");
            return (Criteria) this;
        }

        public Criteria andIsNameIn(List<String> values) {
            addCriterion("is_name in", values, "isName");
            return (Criteria) this;
        }

        public Criteria andIsNameNotIn(List<String> values) {
            addCriterion("is_name not in", values, "isName");
            return (Criteria) this;
        }

        public Criteria andIsNameBetween(String value1, String value2) {
            addCriterion("is_name between", value1, value2, "isName");
            return (Criteria) this;
        }

        public Criteria andIsNameNotBetween(String value1, String value2) {
            addCriterion("is_name not between", value1, value2, "isName");
            return (Criteria) this;
        }

        public Criteria andIsDdIdIsNull() {
            addCriterion("is_dd_id is null");
            return (Criteria) this;
        }

        public Criteria andIsDdIdIsNotNull() {
            addCriterion("is_dd_id is not null");
            return (Criteria) this;
        }

        public Criteria andIsDdIdEqualTo(Integer value) {
            addCriterion("is_dd_id =", value, "isDdId");
            return (Criteria) this;
        }

        public Criteria andIsDdIdNotEqualTo(Integer value) {
            addCriterion("is_dd_id <>", value, "isDdId");
            return (Criteria) this;
        }

        public Criteria andIsDdIdGreaterThan(Integer value) {
            addCriterion("is_dd_id >", value, "isDdId");
            return (Criteria) this;
        }

        public Criteria andIsDdIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_dd_id >=", value, "isDdId");
            return (Criteria) this;
        }

        public Criteria andIsDdIdLessThan(Integer value) {
            addCriterion("is_dd_id <", value, "isDdId");
            return (Criteria) this;
        }

        public Criteria andIsDdIdLessThanOrEqualTo(Integer value) {
            addCriterion("is_dd_id <=", value, "isDdId");
            return (Criteria) this;
        }

        public Criteria andIsDdIdIn(List<Integer> values) {
            addCriterion("is_dd_id in", values, "isDdId");
            return (Criteria) this;
        }

        public Criteria andIsDdIdNotIn(List<Integer> values) {
            addCriterion("is_dd_id not in", values, "isDdId");
            return (Criteria) this;
        }

        public Criteria andIsDdIdBetween(Integer value1, Integer value2) {
            addCriterion("is_dd_id between", value1, value2, "isDdId");
            return (Criteria) this;
        }

        public Criteria andIsDdIdNotBetween(Integer value1, Integer value2) {
            addCriterion("is_dd_id not between", value1, value2, "isDdId");
            return (Criteria) this;
        }

        public Criteria andIsDlIdIsNull() {
            addCriterion("is_dl_id is null");
            return (Criteria) this;
        }

        public Criteria andIsDlIdIsNotNull() {
            addCriterion("is_dl_id is not null");
            return (Criteria) this;
        }

        public Criteria andIsDlIdEqualTo(Integer value) {
            addCriterion("is_dl_id =", value, "isDlId");
            return (Criteria) this;
        }

        public Criteria andIsDlIdNotEqualTo(Integer value) {
            addCriterion("is_dl_id <>", value, "isDlId");
            return (Criteria) this;
        }

        public Criteria andIsDlIdGreaterThan(Integer value) {
            addCriterion("is_dl_id >", value, "isDlId");
            return (Criteria) this;
        }

        public Criteria andIsDlIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_dl_id >=", value, "isDlId");
            return (Criteria) this;
        }

        public Criteria andIsDlIdLessThan(Integer value) {
            addCriterion("is_dl_id <", value, "isDlId");
            return (Criteria) this;
        }

        public Criteria andIsDlIdLessThanOrEqualTo(Integer value) {
            addCriterion("is_dl_id <=", value, "isDlId");
            return (Criteria) this;
        }

        public Criteria andIsDlIdIn(List<Integer> values) {
            addCriterion("is_dl_id in", values, "isDlId");
            return (Criteria) this;
        }

        public Criteria andIsDlIdNotIn(List<Integer> values) {
            addCriterion("is_dl_id not in", values, "isDlId");
            return (Criteria) this;
        }

        public Criteria andIsDlIdBetween(Integer value1, Integer value2) {
            addCriterion("is_dl_id between", value1, value2, "isDlId");
            return (Criteria) this;
        }

        public Criteria andIsDlIdNotBetween(Integer value1, Integer value2) {
            addCriterion("is_dl_id not between", value1, value2, "isDlId");
            return (Criteria) this;
        }

        public Criteria andIsXhIdIsNull() {
            addCriterion("is_xh_id is null");
            return (Criteria) this;
        }

        public Criteria andIsXhIdIsNotNull() {
            addCriterion("is_xh_id is not null");
            return (Criteria) this;
        }

        public Criteria andIsXhIdEqualTo(Integer value) {
            addCriterion("is_xh_id =", value, "isXhId");
            return (Criteria) this;
        }

        public Criteria andIsXhIdNotEqualTo(Integer value) {
            addCriterion("is_xh_id <>", value, "isXhId");
            return (Criteria) this;
        }

        public Criteria andIsXhIdGreaterThan(Integer value) {
            addCriterion("is_xh_id >", value, "isXhId");
            return (Criteria) this;
        }

        public Criteria andIsXhIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_xh_id >=", value, "isXhId");
            return (Criteria) this;
        }

        public Criteria andIsXhIdLessThan(Integer value) {
            addCriterion("is_xh_id <", value, "isXhId");
            return (Criteria) this;
        }

        public Criteria andIsXhIdLessThanOrEqualTo(Integer value) {
            addCriterion("is_xh_id <=", value, "isXhId");
            return (Criteria) this;
        }

        public Criteria andIsXhIdIn(List<Integer> values) {
            addCriterion("is_xh_id in", values, "isXhId");
            return (Criteria) this;
        }

        public Criteria andIsXhIdNotIn(List<Integer> values) {
            addCriterion("is_xh_id not in", values, "isXhId");
            return (Criteria) this;
        }

        public Criteria andIsXhIdBetween(Integer value1, Integer value2) {
            addCriterion("is_xh_id between", value1, value2, "isXhId");
            return (Criteria) this;
        }

        public Criteria andIsXhIdNotBetween(Integer value1, Integer value2) {
            addCriterion("is_xh_id not between", value1, value2, "isXhId");
            return (Criteria) this;
        }

        public Criteria andIsWhNameIsNull() {
            addCriterion("is_wh_name is null");
            return (Criteria) this;
        }

        public Criteria andIsWhNameIsNotNull() {
            addCriterion("is_wh_name is not null");
            return (Criteria) this;
        }

        public Criteria andIsWhNameEqualTo(String value) {
            addCriterion("is_wh_name =", value, "isWhName");
            return (Criteria) this;
        }

        public Criteria andIsWhNameNotEqualTo(String value) {
            addCriterion("is_wh_name <>", value, "isWhName");
            return (Criteria) this;
        }

        public Criteria andIsWhNameGreaterThan(String value) {
            addCriterion("is_wh_name >", value, "isWhName");
            return (Criteria) this;
        }

        public Criteria andIsWhNameGreaterThanOrEqualTo(String value) {
            addCriterion("is_wh_name >=", value, "isWhName");
            return (Criteria) this;
        }

        public Criteria andIsWhNameLessThan(String value) {
            addCriterion("is_wh_name <", value, "isWhName");
            return (Criteria) this;
        }

        public Criteria andIsWhNameLessThanOrEqualTo(String value) {
            addCriterion("is_wh_name <=", value, "isWhName");
            return (Criteria) this;
        }

        public Criteria andIsWhNameLike(String value) {
            addCriterion("is_wh_name like", value, "isWhName");
            return (Criteria) this;
        }

        public Criteria andIsWhNameNotLike(String value) {
            addCriterion("is_wh_name not like", value, "isWhName");
            return (Criteria) this;
        }

        public Criteria andIsWhNameIn(List<String> values) {
            addCriterion("is_wh_name in", values, "isWhName");
            return (Criteria) this;
        }

        public Criteria andIsWhNameNotIn(List<String> values) {
            addCriterion("is_wh_name not in", values, "isWhName");
            return (Criteria) this;
        }

        public Criteria andIsWhNameBetween(String value1, String value2) {
            addCriterion("is_wh_name between", value1, value2, "isWhName");
            return (Criteria) this;
        }

        public Criteria andIsWhNameNotBetween(String value1, String value2) {
            addCriterion("is_wh_name not between", value1, value2, "isWhName");
            return (Criteria) this;
        }

        public Criteria andIsCreateIsNull() {
            addCriterion("is_create is null");
            return (Criteria) this;
        }

        public Criteria andIsCreateIsNotNull() {
            addCriterion("is_create is not null");
            return (Criteria) this;
        }

        public Criteria andIsCreateEqualTo(Long value) {
            addCriterion("is_create =", value, "isCreate");
            return (Criteria) this;
        }

        public Criteria andIsCreateNotEqualTo(Long value) {
            addCriterion("is_create <>", value, "isCreate");
            return (Criteria) this;
        }

        public Criteria andIsCreateGreaterThan(Long value) {
            addCriterion("is_create >", value, "isCreate");
            return (Criteria) this;
        }

        public Criteria andIsCreateGreaterThanOrEqualTo(Long value) {
            addCriterion("is_create >=", value, "isCreate");
            return (Criteria) this;
        }

        public Criteria andIsCreateLessThan(Long value) {
            addCriterion("is_create <", value, "isCreate");
            return (Criteria) this;
        }

        public Criteria andIsCreateLessThanOrEqualTo(Long value) {
            addCriterion("is_create <=", value, "isCreate");
            return (Criteria) this;
        }

        public Criteria andIsCreateIn(List<Long> values) {
            addCriterion("is_create in", values, "isCreate");
            return (Criteria) this;
        }

        public Criteria andIsCreateNotIn(List<Long> values) {
            addCriterion("is_create not in", values, "isCreate");
            return (Criteria) this;
        }

        public Criteria andIsCreateBetween(Long value1, Long value2) {
            addCriterion("is_create between", value1, value2, "isCreate");
            return (Criteria) this;
        }

        public Criteria andIsCreateNotBetween(Long value1, Long value2) {
            addCriterion("is_create not between", value1, value2, "isCreate");
            return (Criteria) this;
        }

        public Criteria andIsModifiedIsNull() {
            addCriterion("is_modified is null");
            return (Criteria) this;
        }

        public Criteria andIsModifiedIsNotNull() {
            addCriterion("is_modified is not null");
            return (Criteria) this;
        }

        public Criteria andIsModifiedEqualTo(Long value) {
            addCriterion("is_modified =", value, "isModified");
            return (Criteria) this;
        }

        public Criteria andIsModifiedNotEqualTo(Long value) {
            addCriterion("is_modified <>", value, "isModified");
            return (Criteria) this;
        }

        public Criteria andIsModifiedGreaterThan(Long value) {
            addCriterion("is_modified >", value, "isModified");
            return (Criteria) this;
        }

        public Criteria andIsModifiedGreaterThanOrEqualTo(Long value) {
            addCriterion("is_modified >=", value, "isModified");
            return (Criteria) this;
        }

        public Criteria andIsModifiedLessThan(Long value) {
            addCriterion("is_modified <", value, "isModified");
            return (Criteria) this;
        }

        public Criteria andIsModifiedLessThanOrEqualTo(Long value) {
            addCriterion("is_modified <=", value, "isModified");
            return (Criteria) this;
        }

        public Criteria andIsModifiedIn(List<Long> values) {
            addCriterion("is_modified in", values, "isModified");
            return (Criteria) this;
        }

        public Criteria andIsModifiedNotIn(List<Long> values) {
            addCriterion("is_modified not in", values, "isModified");
            return (Criteria) this;
        }

        public Criteria andIsModifiedBetween(Long value1, Long value2) {
            addCriterion("is_modified between", value1, value2, "isModified");
            return (Criteria) this;
        }

        public Criteria andIsModifiedNotBetween(Long value1, Long value2) {
            addCriterion("is_modified not between", value1, value2, "isModified");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ts_is
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ts_is
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}