package com.jupiter.ts.model;

public class Intersection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_is.id
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_is.is_dd
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    private String isDd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_is.is_dl
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    private String isDl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_is.is_xh
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    private String isXh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_is.is_sd
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    private Integer isSd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_is.is_xw
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    private Integer isXw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_is.is_wh
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    private String isWh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_is.is_lb
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    private String isLb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_is.is_create
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    private Long isCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_is.is_modified
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    private Long isModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_is.is_name
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    private String isName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_is.id
     *
     * @return the value of ts_is.id
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_is.id
     *
     * @param id the value for ts_is.id
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_is.is_dd
     *
     * @return the value of ts_is.is_dd
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    public String getIsDd() {
        return isDd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_is.is_dd
     *
     * @param isDd the value for ts_is.is_dd
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    public void setIsDd(String isDd) {
        this.isDd = isDd == null ? null : isDd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_is.is_dl
     *
     * @return the value of ts_is.is_dl
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    public String getIsDl() {
        return isDl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_is.is_dl
     *
     * @param isDl the value for ts_is.is_dl
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    public void setIsDl(String isDl) {
        this.isDl = isDl == null ? null : isDl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_is.is_xh
     *
     * @return the value of ts_is.is_xh
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    public String getIsXh() {
        return isXh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_is.is_xh
     *
     * @param isXh the value for ts_is.is_xh
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    public void setIsXh(String isXh) {
        this.isXh = isXh == null ? null : isXh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_is.is_sd
     *
     * @return the value of ts_is.is_sd
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    public Integer getIsSd() {
        return isSd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_is.is_sd
     *
     * @param isSd the value for ts_is.is_sd
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    public void setIsSd(Integer isSd) {
        this.isSd = isSd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_is.is_xw
     *
     * @return the value of ts_is.is_xw
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    public Integer getIsXw() {
        return isXw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_is.is_xw
     *
     * @param isXw the value for ts_is.is_xw
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    public void setIsXw(Integer isXw) {
        this.isXw = isXw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_is.is_wh
     *
     * @return the value of ts_is.is_wh
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    public String getIsWh() {
        return isWh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_is.is_wh
     *
     * @param isWh the value for ts_is.is_wh
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    public void setIsWh(String isWh) {
        this.isWh = isWh == null ? null : isWh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_is.is_lb
     *
     * @return the value of ts_is.is_lb
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    public String getIsLb() {
        return isLb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_is.is_lb
     *
     * @param isLb the value for ts_is.is_lb
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    public void setIsLb(String isLb) {
        this.isLb = isLb == null ? null : isLb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_is.is_create
     *
     * @return the value of ts_is.is_create
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    public Long getIsCreate() {
        return isCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_is.is_create
     *
     * @param isCreate the value for ts_is.is_create
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    public void setIsCreate(Long isCreate) {
        this.isCreate = isCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_is.is_modified
     *
     * @return the value of ts_is.is_modified
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    public Long getIsModified() {
        return isModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_is.is_modified
     *
     * @param isModified the value for ts_is.is_modified
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    public void setIsModified(Long isModified) {
        this.isModified = isModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_is.is_name
     *
     * @return the value of ts_is.is_name
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    public String getIsName() {
        return isName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_is.is_name
     *
     * @param isName the value for ts_is.is_name
     *
     * @mbg.generated Sat Oct 26 15:51:37 GMT+08:00 2019
     */
    public void setIsName(String isName) {
        this.isName = isName == null ? null : isName.trim();
    }
}