package com.jupiter.ts.model;

public class Intersection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_is.id
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_is.is_name
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    private String isName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_is.is_dd_id
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    private Integer isDdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_is.is_dl_id
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    private Integer isDlId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_is.is_xh_id
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    private Integer isXhId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_is.is_wh_name
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    private String isWhName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_is.is_create
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    private Long isCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_is.is_modified
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    private Long isModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_is.is_xw_num
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    private Integer isXwNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_is.id
     *
     * @return the value of ts_is.id
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_is.id
     *
     * @param id the value for ts_is.id
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_is.is_name
     *
     * @return the value of ts_is.is_name
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public String getIsName() {
        return isName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_is.is_name
     *
     * @param isName the value for ts_is.is_name
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public void setIsName(String isName) {
        this.isName = isName == null ? null : isName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_is.is_dd_id
     *
     * @return the value of ts_is.is_dd_id
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public Integer getIsDdId() {
        return isDdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_is.is_dd_id
     *
     * @param isDdId the value for ts_is.is_dd_id
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public void setIsDdId(Integer isDdId) {
        this.isDdId = isDdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_is.is_dl_id
     *
     * @return the value of ts_is.is_dl_id
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public Integer getIsDlId() {
        return isDlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_is.is_dl_id
     *
     * @param isDlId the value for ts_is.is_dl_id
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public void setIsDlId(Integer isDlId) {
        this.isDlId = isDlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_is.is_xh_id
     *
     * @return the value of ts_is.is_xh_id
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public Integer getIsXhId() {
        return isXhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_is.is_xh_id
     *
     * @param isXhId the value for ts_is.is_xh_id
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public void setIsXhId(Integer isXhId) {
        this.isXhId = isXhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_is.is_wh_name
     *
     * @return the value of ts_is.is_wh_name
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public String getIsWhName() {
        return isWhName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_is.is_wh_name
     *
     * @param isWhName the value for ts_is.is_wh_name
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public void setIsWhName(String isWhName) {
        this.isWhName = isWhName == null ? null : isWhName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_is.is_create
     *
     * @return the value of ts_is.is_create
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public Long getIsCreate() {
        return isCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_is.is_create
     *
     * @param isCreate the value for ts_is.is_create
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public void setIsCreate(Long isCreate) {
        this.isCreate = isCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_is.is_modified
     *
     * @return the value of ts_is.is_modified
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public Long getIsModified() {
        return isModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_is.is_modified
     *
     * @param isModified the value for ts_is.is_modified
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public void setIsModified(Long isModified) {
        this.isModified = isModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_is.is_xw_num
     *
     * @return the value of ts_is.is_xw_num
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public Integer getIsXwNum() {
        return isXwNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_is.is_xw_num
     *
     * @param isXwNum the value for ts_is.is_xw_num
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public void setIsXwNum(Integer isXwNum) {
        this.isXwNum = isXwNum;
    }
}