package com.jupiter.ts.model;

public class Interval {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sd.id
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sd.sd_start
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    private String sdStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sd.sd_end
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    private String sdEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sd.sd_is_id
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    private Integer sdIsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sd.sd_fa_id
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    private Integer sdFaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sd.sd_name
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    private String sdName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sd.sd_create
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    private Long sdCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sd.sd_modified
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    private Long sdModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sd.id
     *
     * @return the value of ts_sd.id
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sd.id
     *
     * @param id the value for ts_sd.id
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sd.sd_start
     *
     * @return the value of ts_sd.sd_start
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public String getSdStart() {
        return sdStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sd.sd_start
     *
     * @param sdStart the value for ts_sd.sd_start
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public void setSdStart(String sdStart) {
        this.sdStart = sdStart == null ? null : sdStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sd.sd_end
     *
     * @return the value of ts_sd.sd_end
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public String getSdEnd() {
        return sdEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sd.sd_end
     *
     * @param sdEnd the value for ts_sd.sd_end
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public void setSdEnd(String sdEnd) {
        this.sdEnd = sdEnd == null ? null : sdEnd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sd.sd_is_id
     *
     * @return the value of ts_sd.sd_is_id
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public Integer getSdIsId() {
        return sdIsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sd.sd_is_id
     *
     * @param sdIsId the value for ts_sd.sd_is_id
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public void setSdIsId(Integer sdIsId) {
        this.sdIsId = sdIsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sd.sd_fa_id
     *
     * @return the value of ts_sd.sd_fa_id
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public Integer getSdFaId() {
        return sdFaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sd.sd_fa_id
     *
     * @param sdFaId the value for ts_sd.sd_fa_id
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public void setSdFaId(Integer sdFaId) {
        this.sdFaId = sdFaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sd.sd_name
     *
     * @return the value of ts_sd.sd_name
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public String getSdName() {
        return sdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sd.sd_name
     *
     * @param sdName the value for ts_sd.sd_name
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public void setSdName(String sdName) {
        this.sdName = sdName == null ? null : sdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sd.sd_create
     *
     * @return the value of ts_sd.sd_create
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public Long getSdCreate() {
        return sdCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sd.sd_create
     *
     * @param sdCreate the value for ts_sd.sd_create
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public void setSdCreate(Long sdCreate) {
        this.sdCreate = sdCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sd.sd_modified
     *
     * @return the value of ts_sd.sd_modified
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public Long getSdModified() {
        return sdModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sd.sd_modified
     *
     * @param sdModified the value for ts_sd.sd_modified
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    public void setSdModified(Long sdModified) {
        this.sdModified = sdModified;
    }
}