package com.jupiter.ts.model;

import java.util.ArrayList;
import java.util.List;

public class PhaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ts_xw
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ts_xw
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ts_xw
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_xw
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public PhaseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_xw
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_xw
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_xw
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_xw
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_xw
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_xw
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_xw
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_xw
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_xw
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_xw
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ts_xw
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andXwFaIdIsNull() {
            addCriterion("xw_fa_id is null");
            return (Criteria) this;
        }

        public Criteria andXwFaIdIsNotNull() {
            addCriterion("xw_fa_id is not null");
            return (Criteria) this;
        }

        public Criteria andXwFaIdEqualTo(Integer value) {
            addCriterion("xw_fa_id =", value, "xwFaId");
            return (Criteria) this;
        }

        public Criteria andXwFaIdNotEqualTo(Integer value) {
            addCriterion("xw_fa_id <>", value, "xwFaId");
            return (Criteria) this;
        }

        public Criteria andXwFaIdGreaterThan(Integer value) {
            addCriterion("xw_fa_id >", value, "xwFaId");
            return (Criteria) this;
        }

        public Criteria andXwFaIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("xw_fa_id >=", value, "xwFaId");
            return (Criteria) this;
        }

        public Criteria andXwFaIdLessThan(Integer value) {
            addCriterion("xw_fa_id <", value, "xwFaId");
            return (Criteria) this;
        }

        public Criteria andXwFaIdLessThanOrEqualTo(Integer value) {
            addCriterion("xw_fa_id <=", value, "xwFaId");
            return (Criteria) this;
        }

        public Criteria andXwFaIdIn(List<Integer> values) {
            addCriterion("xw_fa_id in", values, "xwFaId");
            return (Criteria) this;
        }

        public Criteria andXwFaIdNotIn(List<Integer> values) {
            addCriterion("xw_fa_id not in", values, "xwFaId");
            return (Criteria) this;
        }

        public Criteria andXwFaIdBetween(Integer value1, Integer value2) {
            addCriterion("xw_fa_id between", value1, value2, "xwFaId");
            return (Criteria) this;
        }

        public Criteria andXwFaIdNotBetween(Integer value1, Integer value2) {
            addCriterion("xw_fa_id not between", value1, value2, "xwFaId");
            return (Criteria) this;
        }

        public Criteria andXwNameIsNull() {
            addCriterion("xw_name is null");
            return (Criteria) this;
        }

        public Criteria andXwNameIsNotNull() {
            addCriterion("xw_name is not null");
            return (Criteria) this;
        }

        public Criteria andXwNameEqualTo(String value) {
            addCriterion("xw_name =", value, "xwName");
            return (Criteria) this;
        }

        public Criteria andXwNameNotEqualTo(String value) {
            addCriterion("xw_name <>", value, "xwName");
            return (Criteria) this;
        }

        public Criteria andXwNameGreaterThan(String value) {
            addCriterion("xw_name >", value, "xwName");
            return (Criteria) this;
        }

        public Criteria andXwNameGreaterThanOrEqualTo(String value) {
            addCriterion("xw_name >=", value, "xwName");
            return (Criteria) this;
        }

        public Criteria andXwNameLessThan(String value) {
            addCriterion("xw_name <", value, "xwName");
            return (Criteria) this;
        }

        public Criteria andXwNameLessThanOrEqualTo(String value) {
            addCriterion("xw_name <=", value, "xwName");
            return (Criteria) this;
        }

        public Criteria andXwNameLike(String value) {
            addCriterion("xw_name like", value, "xwName");
            return (Criteria) this;
        }

        public Criteria andXwNameNotLike(String value) {
            addCriterion("xw_name not like", value, "xwName");
            return (Criteria) this;
        }

        public Criteria andXwNameIn(List<String> values) {
            addCriterion("xw_name in", values, "xwName");
            return (Criteria) this;
        }

        public Criteria andXwNameNotIn(List<String> values) {
            addCriterion("xw_name not in", values, "xwName");
            return (Criteria) this;
        }

        public Criteria andXwNameBetween(String value1, String value2) {
            addCriterion("xw_name between", value1, value2, "xwName");
            return (Criteria) this;
        }

        public Criteria andXwNameNotBetween(String value1, String value2) {
            addCriterion("xw_name not between", value1, value2, "xwName");
            return (Criteria) this;
        }

        public Criteria andXwGreenIsNull() {
            addCriterion("xw_green is null");
            return (Criteria) this;
        }

        public Criteria andXwGreenIsNotNull() {
            addCriterion("xw_green is not null");
            return (Criteria) this;
        }

        public Criteria andXwGreenEqualTo(Integer value) {
            addCriterion("xw_green =", value, "xwGreen");
            return (Criteria) this;
        }

        public Criteria andXwGreenNotEqualTo(Integer value) {
            addCriterion("xw_green <>", value, "xwGreen");
            return (Criteria) this;
        }

        public Criteria andXwGreenGreaterThan(Integer value) {
            addCriterion("xw_green >", value, "xwGreen");
            return (Criteria) this;
        }

        public Criteria andXwGreenGreaterThanOrEqualTo(Integer value) {
            addCriterion("xw_green >=", value, "xwGreen");
            return (Criteria) this;
        }

        public Criteria andXwGreenLessThan(Integer value) {
            addCriterion("xw_green <", value, "xwGreen");
            return (Criteria) this;
        }

        public Criteria andXwGreenLessThanOrEqualTo(Integer value) {
            addCriterion("xw_green <=", value, "xwGreen");
            return (Criteria) this;
        }

        public Criteria andXwGreenIn(List<Integer> values) {
            addCriterion("xw_green in", values, "xwGreen");
            return (Criteria) this;
        }

        public Criteria andXwGreenNotIn(List<Integer> values) {
            addCriterion("xw_green not in", values, "xwGreen");
            return (Criteria) this;
        }

        public Criteria andXwGreenBetween(Integer value1, Integer value2) {
            addCriterion("xw_green between", value1, value2, "xwGreen");
            return (Criteria) this;
        }

        public Criteria andXwGreenNotBetween(Integer value1, Integer value2) {
            addCriterion("xw_green not between", value1, value2, "xwGreen");
            return (Criteria) this;
        }

        public Criteria andXwYellowIsNull() {
            addCriterion("xw_yellow is null");
            return (Criteria) this;
        }

        public Criteria andXwYellowIsNotNull() {
            addCriterion("xw_yellow is not null");
            return (Criteria) this;
        }

        public Criteria andXwYellowEqualTo(Integer value) {
            addCriterion("xw_yellow =", value, "xwYellow");
            return (Criteria) this;
        }

        public Criteria andXwYellowNotEqualTo(Integer value) {
            addCriterion("xw_yellow <>", value, "xwYellow");
            return (Criteria) this;
        }

        public Criteria andXwYellowGreaterThan(Integer value) {
            addCriterion("xw_yellow >", value, "xwYellow");
            return (Criteria) this;
        }

        public Criteria andXwYellowGreaterThanOrEqualTo(Integer value) {
            addCriterion("xw_yellow >=", value, "xwYellow");
            return (Criteria) this;
        }

        public Criteria andXwYellowLessThan(Integer value) {
            addCriterion("xw_yellow <", value, "xwYellow");
            return (Criteria) this;
        }

        public Criteria andXwYellowLessThanOrEqualTo(Integer value) {
            addCriterion("xw_yellow <=", value, "xwYellow");
            return (Criteria) this;
        }

        public Criteria andXwYellowIn(List<Integer> values) {
            addCriterion("xw_yellow in", values, "xwYellow");
            return (Criteria) this;
        }

        public Criteria andXwYellowNotIn(List<Integer> values) {
            addCriterion("xw_yellow not in", values, "xwYellow");
            return (Criteria) this;
        }

        public Criteria andXwYellowBetween(Integer value1, Integer value2) {
            addCriterion("xw_yellow between", value1, value2, "xwYellow");
            return (Criteria) this;
        }

        public Criteria andXwYellowNotBetween(Integer value1, Integer value2) {
            addCriterion("xw_yellow not between", value1, value2, "xwYellow");
            return (Criteria) this;
        }

        public Criteria andXwRedIsNull() {
            addCriterion("xw_red is null");
            return (Criteria) this;
        }

        public Criteria andXwRedIsNotNull() {
            addCriterion("xw_red is not null");
            return (Criteria) this;
        }

        public Criteria andXwRedEqualTo(Integer value) {
            addCriterion("xw_red =", value, "xwRed");
            return (Criteria) this;
        }

        public Criteria andXwRedNotEqualTo(Integer value) {
            addCriterion("xw_red <>", value, "xwRed");
            return (Criteria) this;
        }

        public Criteria andXwRedGreaterThan(Integer value) {
            addCriterion("xw_red >", value, "xwRed");
            return (Criteria) this;
        }

        public Criteria andXwRedGreaterThanOrEqualTo(Integer value) {
            addCriterion("xw_red >=", value, "xwRed");
            return (Criteria) this;
        }

        public Criteria andXwRedLessThan(Integer value) {
            addCriterion("xw_red <", value, "xwRed");
            return (Criteria) this;
        }

        public Criteria andXwRedLessThanOrEqualTo(Integer value) {
            addCriterion("xw_red <=", value, "xwRed");
            return (Criteria) this;
        }

        public Criteria andXwRedIn(List<Integer> values) {
            addCriterion("xw_red in", values, "xwRed");
            return (Criteria) this;
        }

        public Criteria andXwRedNotIn(List<Integer> values) {
            addCriterion("xw_red not in", values, "xwRed");
            return (Criteria) this;
        }

        public Criteria andXwRedBetween(Integer value1, Integer value2) {
            addCriterion("xw_red between", value1, value2, "xwRed");
            return (Criteria) this;
        }

        public Criteria andXwRedNotBetween(Integer value1, Integer value2) {
            addCriterion("xw_red not between", value1, value2, "xwRed");
            return (Criteria) this;
        }

        public Criteria andXwVehicleGreenIsNull() {
            addCriterion("xw_vehicle_green is null");
            return (Criteria) this;
        }

        public Criteria andXwVehicleGreenIsNotNull() {
            addCriterion("xw_vehicle_green is not null");
            return (Criteria) this;
        }

        public Criteria andXwVehicleGreenEqualTo(Integer value) {
            addCriterion("xw_vehicle_green =", value, "xwVehicleGreen");
            return (Criteria) this;
        }

        public Criteria andXwVehicleGreenNotEqualTo(Integer value) {
            addCriterion("xw_vehicle_green <>", value, "xwVehicleGreen");
            return (Criteria) this;
        }

        public Criteria andXwVehicleGreenGreaterThan(Integer value) {
            addCriterion("xw_vehicle_green >", value, "xwVehicleGreen");
            return (Criteria) this;
        }

        public Criteria andXwVehicleGreenGreaterThanOrEqualTo(Integer value) {
            addCriterion("xw_vehicle_green >=", value, "xwVehicleGreen");
            return (Criteria) this;
        }

        public Criteria andXwVehicleGreenLessThan(Integer value) {
            addCriterion("xw_vehicle_green <", value, "xwVehicleGreen");
            return (Criteria) this;
        }

        public Criteria andXwVehicleGreenLessThanOrEqualTo(Integer value) {
            addCriterion("xw_vehicle_green <=", value, "xwVehicleGreen");
            return (Criteria) this;
        }

        public Criteria andXwVehicleGreenIn(List<Integer> values) {
            addCriterion("xw_vehicle_green in", values, "xwVehicleGreen");
            return (Criteria) this;
        }

        public Criteria andXwVehicleGreenNotIn(List<Integer> values) {
            addCriterion("xw_vehicle_green not in", values, "xwVehicleGreen");
            return (Criteria) this;
        }

        public Criteria andXwVehicleGreenBetween(Integer value1, Integer value2) {
            addCriterion("xw_vehicle_green between", value1, value2, "xwVehicleGreen");
            return (Criteria) this;
        }

        public Criteria andXwVehicleGreenNotBetween(Integer value1, Integer value2) {
            addCriterion("xw_vehicle_green not between", value1, value2, "xwVehicleGreen");
            return (Criteria) this;
        }

        public Criteria andXwVehicleRedIsNull() {
            addCriterion("xw_vehicle_red is null");
            return (Criteria) this;
        }

        public Criteria andXwVehicleRedIsNotNull() {
            addCriterion("xw_vehicle_red is not null");
            return (Criteria) this;
        }

        public Criteria andXwVehicleRedEqualTo(Integer value) {
            addCriterion("xw_vehicle_red =", value, "xwVehicleRed");
            return (Criteria) this;
        }

        public Criteria andXwVehicleRedNotEqualTo(Integer value) {
            addCriterion("xw_vehicle_red <>", value, "xwVehicleRed");
            return (Criteria) this;
        }

        public Criteria andXwVehicleRedGreaterThan(Integer value) {
            addCriterion("xw_vehicle_red >", value, "xwVehicleRed");
            return (Criteria) this;
        }

        public Criteria andXwVehicleRedGreaterThanOrEqualTo(Integer value) {
            addCriterion("xw_vehicle_red >=", value, "xwVehicleRed");
            return (Criteria) this;
        }

        public Criteria andXwVehicleRedLessThan(Integer value) {
            addCriterion("xw_vehicle_red <", value, "xwVehicleRed");
            return (Criteria) this;
        }

        public Criteria andXwVehicleRedLessThanOrEqualTo(Integer value) {
            addCriterion("xw_vehicle_red <=", value, "xwVehicleRed");
            return (Criteria) this;
        }

        public Criteria andXwVehicleRedIn(List<Integer> values) {
            addCriterion("xw_vehicle_red in", values, "xwVehicleRed");
            return (Criteria) this;
        }

        public Criteria andXwVehicleRedNotIn(List<Integer> values) {
            addCriterion("xw_vehicle_red not in", values, "xwVehicleRed");
            return (Criteria) this;
        }

        public Criteria andXwVehicleRedBetween(Integer value1, Integer value2) {
            addCriterion("xw_vehicle_red between", value1, value2, "xwVehicleRed");
            return (Criteria) this;
        }

        public Criteria andXwVehicleRedNotBetween(Integer value1, Integer value2) {
            addCriterion("xw_vehicle_red not between", value1, value2, "xwVehicleRed");
            return (Criteria) this;
        }

        public Criteria andXwWalkerGreenIsNull() {
            addCriterion("xw_walker_green is null");
            return (Criteria) this;
        }

        public Criteria andXwWalkerGreenIsNotNull() {
            addCriterion("xw_walker_green is not null");
            return (Criteria) this;
        }

        public Criteria andXwWalkerGreenEqualTo(Integer value) {
            addCriterion("xw_walker_green =", value, "xwWalkerGreen");
            return (Criteria) this;
        }

        public Criteria andXwWalkerGreenNotEqualTo(Integer value) {
            addCriterion("xw_walker_green <>", value, "xwWalkerGreen");
            return (Criteria) this;
        }

        public Criteria andXwWalkerGreenGreaterThan(Integer value) {
            addCriterion("xw_walker_green >", value, "xwWalkerGreen");
            return (Criteria) this;
        }

        public Criteria andXwWalkerGreenGreaterThanOrEqualTo(Integer value) {
            addCriterion("xw_walker_green >=", value, "xwWalkerGreen");
            return (Criteria) this;
        }

        public Criteria andXwWalkerGreenLessThan(Integer value) {
            addCriterion("xw_walker_green <", value, "xwWalkerGreen");
            return (Criteria) this;
        }

        public Criteria andXwWalkerGreenLessThanOrEqualTo(Integer value) {
            addCriterion("xw_walker_green <=", value, "xwWalkerGreen");
            return (Criteria) this;
        }

        public Criteria andXwWalkerGreenIn(List<Integer> values) {
            addCriterion("xw_walker_green in", values, "xwWalkerGreen");
            return (Criteria) this;
        }

        public Criteria andXwWalkerGreenNotIn(List<Integer> values) {
            addCriterion("xw_walker_green not in", values, "xwWalkerGreen");
            return (Criteria) this;
        }

        public Criteria andXwWalkerGreenBetween(Integer value1, Integer value2) {
            addCriterion("xw_walker_green between", value1, value2, "xwWalkerGreen");
            return (Criteria) this;
        }

        public Criteria andXwWalkerGreenNotBetween(Integer value1, Integer value2) {
            addCriterion("xw_walker_green not between", value1, value2, "xwWalkerGreen");
            return (Criteria) this;
        }

        public Criteria andXwWalkerRedIsNull() {
            addCriterion("xw_walker_red is null");
            return (Criteria) this;
        }

        public Criteria andXwWalkerRedIsNotNull() {
            addCriterion("xw_walker_red is not null");
            return (Criteria) this;
        }

        public Criteria andXwWalkerRedEqualTo(Integer value) {
            addCriterion("xw_walker_red =", value, "xwWalkerRed");
            return (Criteria) this;
        }

        public Criteria andXwWalkerRedNotEqualTo(Integer value) {
            addCriterion("xw_walker_red <>", value, "xwWalkerRed");
            return (Criteria) this;
        }

        public Criteria andXwWalkerRedGreaterThan(Integer value) {
            addCriterion("xw_walker_red >", value, "xwWalkerRed");
            return (Criteria) this;
        }

        public Criteria andXwWalkerRedGreaterThanOrEqualTo(Integer value) {
            addCriterion("xw_walker_red >=", value, "xwWalkerRed");
            return (Criteria) this;
        }

        public Criteria andXwWalkerRedLessThan(Integer value) {
            addCriterion("xw_walker_red <", value, "xwWalkerRed");
            return (Criteria) this;
        }

        public Criteria andXwWalkerRedLessThanOrEqualTo(Integer value) {
            addCriterion("xw_walker_red <=", value, "xwWalkerRed");
            return (Criteria) this;
        }

        public Criteria andXwWalkerRedIn(List<Integer> values) {
            addCriterion("xw_walker_red in", values, "xwWalkerRed");
            return (Criteria) this;
        }

        public Criteria andXwWalkerRedNotIn(List<Integer> values) {
            addCriterion("xw_walker_red not in", values, "xwWalkerRed");
            return (Criteria) this;
        }

        public Criteria andXwWalkerRedBetween(Integer value1, Integer value2) {
            addCriterion("xw_walker_red between", value1, value2, "xwWalkerRed");
            return (Criteria) this;
        }

        public Criteria andXwWalkerRedNotBetween(Integer value1, Integer value2) {
            addCriterion("xw_walker_red not between", value1, value2, "xwWalkerRed");
            return (Criteria) this;
        }

        public Criteria andXwCreateIsNull() {
            addCriterion("xw_create is null");
            return (Criteria) this;
        }

        public Criteria andXwCreateIsNotNull() {
            addCriterion("xw_create is not null");
            return (Criteria) this;
        }

        public Criteria andXwCreateEqualTo(Long value) {
            addCriterion("xw_create =", value, "xwCreate");
            return (Criteria) this;
        }

        public Criteria andXwCreateNotEqualTo(Long value) {
            addCriterion("xw_create <>", value, "xwCreate");
            return (Criteria) this;
        }

        public Criteria andXwCreateGreaterThan(Long value) {
            addCriterion("xw_create >", value, "xwCreate");
            return (Criteria) this;
        }

        public Criteria andXwCreateGreaterThanOrEqualTo(Long value) {
            addCriterion("xw_create >=", value, "xwCreate");
            return (Criteria) this;
        }

        public Criteria andXwCreateLessThan(Long value) {
            addCriterion("xw_create <", value, "xwCreate");
            return (Criteria) this;
        }

        public Criteria andXwCreateLessThanOrEqualTo(Long value) {
            addCriterion("xw_create <=", value, "xwCreate");
            return (Criteria) this;
        }

        public Criteria andXwCreateIn(List<Long> values) {
            addCriterion("xw_create in", values, "xwCreate");
            return (Criteria) this;
        }

        public Criteria andXwCreateNotIn(List<Long> values) {
            addCriterion("xw_create not in", values, "xwCreate");
            return (Criteria) this;
        }

        public Criteria andXwCreateBetween(Long value1, Long value2) {
            addCriterion("xw_create between", value1, value2, "xwCreate");
            return (Criteria) this;
        }

        public Criteria andXwCreateNotBetween(Long value1, Long value2) {
            addCriterion("xw_create not between", value1, value2, "xwCreate");
            return (Criteria) this;
        }

        public Criteria andXwModofiedIsNull() {
            addCriterion("xw_modofied is null");
            return (Criteria) this;
        }

        public Criteria andXwModofiedIsNotNull() {
            addCriterion("xw_modofied is not null");
            return (Criteria) this;
        }

        public Criteria andXwModofiedEqualTo(Long value) {
            addCriterion("xw_modofied =", value, "xwModofied");
            return (Criteria) this;
        }

        public Criteria andXwModofiedNotEqualTo(Long value) {
            addCriterion("xw_modofied <>", value, "xwModofied");
            return (Criteria) this;
        }

        public Criteria andXwModofiedGreaterThan(Long value) {
            addCriterion("xw_modofied >", value, "xwModofied");
            return (Criteria) this;
        }

        public Criteria andXwModofiedGreaterThanOrEqualTo(Long value) {
            addCriterion("xw_modofied >=", value, "xwModofied");
            return (Criteria) this;
        }

        public Criteria andXwModofiedLessThan(Long value) {
            addCriterion("xw_modofied <", value, "xwModofied");
            return (Criteria) this;
        }

        public Criteria andXwModofiedLessThanOrEqualTo(Long value) {
            addCriterion("xw_modofied <=", value, "xwModofied");
            return (Criteria) this;
        }

        public Criteria andXwModofiedIn(List<Long> values) {
            addCriterion("xw_modofied in", values, "xwModofied");
            return (Criteria) this;
        }

        public Criteria andXwModofiedNotIn(List<Long> values) {
            addCriterion("xw_modofied not in", values, "xwModofied");
            return (Criteria) this;
        }

        public Criteria andXwModofiedBetween(Long value1, Long value2) {
            addCriterion("xw_modofied between", value1, value2, "xwModofied");
            return (Criteria) this;
        }

        public Criteria andXwModofiedNotBetween(Long value1, Long value2) {
            addCriterion("xw_modofied not between", value1, value2, "xwModofied");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ts_xw
     *
     * @mbg.generated do_not_delete_during_merge Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ts_xw
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}