package com.jupiter.ts.model;

public class Phase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_xw.id
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_xw.xw_fa_id
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    private Integer xwFaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_xw.xw_name
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    private String xwName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_xw.xw_green
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    private Integer xwGreen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_xw.xw_yellow
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    private Integer xwYellow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_xw.xw_red
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    private Integer xwRed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_xw.xw_vehicle_green
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    private Integer xwVehicleGreen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_xw.xw_vehicle_red
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    private Integer xwVehicleRed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_xw.xw_walker_green
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    private Integer xwWalkerGreen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_xw.xw_walker_red
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    private Integer xwWalkerRed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_xw.xw_create
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    private Long xwCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_xw.xw_modofied
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    private Long xwModofied;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_xw.id
     *
     * @return the value of ts_xw.id
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_xw.id
     *
     * @param id the value for ts_xw.id
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_xw.xw_fa_id
     *
     * @return the value of ts_xw.xw_fa_id
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public Integer getXwFaId() {
        return xwFaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_xw.xw_fa_id
     *
     * @param xwFaId the value for ts_xw.xw_fa_id
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public void setXwFaId(Integer xwFaId) {
        this.xwFaId = xwFaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_xw.xw_name
     *
     * @return the value of ts_xw.xw_name
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public String getXwName() {
        return xwName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_xw.xw_name
     *
     * @param xwName the value for ts_xw.xw_name
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public void setXwName(String xwName) {
        this.xwName = xwName == null ? null : xwName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_xw.xw_green
     *
     * @return the value of ts_xw.xw_green
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public Integer getXwGreen() {
        return xwGreen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_xw.xw_green
     *
     * @param xwGreen the value for ts_xw.xw_green
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public void setXwGreen(Integer xwGreen) {
        this.xwGreen = xwGreen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_xw.xw_yellow
     *
     * @return the value of ts_xw.xw_yellow
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public Integer getXwYellow() {
        return xwYellow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_xw.xw_yellow
     *
     * @param xwYellow the value for ts_xw.xw_yellow
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public void setXwYellow(Integer xwYellow) {
        this.xwYellow = xwYellow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_xw.xw_red
     *
     * @return the value of ts_xw.xw_red
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public Integer getXwRed() {
        return xwRed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_xw.xw_red
     *
     * @param xwRed the value for ts_xw.xw_red
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public void setXwRed(Integer xwRed) {
        this.xwRed = xwRed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_xw.xw_vehicle_green
     *
     * @return the value of ts_xw.xw_vehicle_green
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public Integer getXwVehicleGreen() {
        return xwVehicleGreen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_xw.xw_vehicle_green
     *
     * @param xwVehicleGreen the value for ts_xw.xw_vehicle_green
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public void setXwVehicleGreen(Integer xwVehicleGreen) {
        this.xwVehicleGreen = xwVehicleGreen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_xw.xw_vehicle_red
     *
     * @return the value of ts_xw.xw_vehicle_red
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public Integer getXwVehicleRed() {
        return xwVehicleRed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_xw.xw_vehicle_red
     *
     * @param xwVehicleRed the value for ts_xw.xw_vehicle_red
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public void setXwVehicleRed(Integer xwVehicleRed) {
        this.xwVehicleRed = xwVehicleRed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_xw.xw_walker_green
     *
     * @return the value of ts_xw.xw_walker_green
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public Integer getXwWalkerGreen() {
        return xwWalkerGreen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_xw.xw_walker_green
     *
     * @param xwWalkerGreen the value for ts_xw.xw_walker_green
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public void setXwWalkerGreen(Integer xwWalkerGreen) {
        this.xwWalkerGreen = xwWalkerGreen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_xw.xw_walker_red
     *
     * @return the value of ts_xw.xw_walker_red
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public Integer getXwWalkerRed() {
        return xwWalkerRed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_xw.xw_walker_red
     *
     * @param xwWalkerRed the value for ts_xw.xw_walker_red
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public void setXwWalkerRed(Integer xwWalkerRed) {
        this.xwWalkerRed = xwWalkerRed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_xw.xw_create
     *
     * @return the value of ts_xw.xw_create
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public Long getXwCreate() {
        return xwCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_xw.xw_create
     *
     * @param xwCreate the value for ts_xw.xw_create
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public void setXwCreate(Long xwCreate) {
        this.xwCreate = xwCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_xw.xw_modofied
     *
     * @return the value of ts_xw.xw_modofied
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public Long getXwModofied() {
        return xwModofied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_xw.xw_modofied
     *
     * @param xwModofied the value for ts_xw.xw_modofied
     *
     * @mbg.generated Sat Nov 09 22:46:37 GMT+08:00 2019
     */
    public void setXwModofied(Long xwModofied) {
        this.xwModofied = xwModofied;
    }
}