package com.jupiter.ts.model;

import java.util.ArrayList;
import java.util.List;

public class ProjectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ts_fa
     *
     * @mbg.generated Sat Nov 09 20:33:22 GMT+08:00 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ts_fa
     *
     * @mbg.generated Sat Nov 09 20:33:22 GMT+08:00 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ts_fa
     *
     * @mbg.generated Sat Nov 09 20:33:22 GMT+08:00 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_fa
     *
     * @mbg.generated Sat Nov 09 20:33:22 GMT+08:00 2019
     */
    public ProjectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_fa
     *
     * @mbg.generated Sat Nov 09 20:33:22 GMT+08:00 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_fa
     *
     * @mbg.generated Sat Nov 09 20:33:22 GMT+08:00 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_fa
     *
     * @mbg.generated Sat Nov 09 20:33:22 GMT+08:00 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_fa
     *
     * @mbg.generated Sat Nov 09 20:33:22 GMT+08:00 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_fa
     *
     * @mbg.generated Sat Nov 09 20:33:22 GMT+08:00 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_fa
     *
     * @mbg.generated Sat Nov 09 20:33:22 GMT+08:00 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_fa
     *
     * @mbg.generated Sat Nov 09 20:33:22 GMT+08:00 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_fa
     *
     * @mbg.generated Sat Nov 09 20:33:22 GMT+08:00 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_fa
     *
     * @mbg.generated Sat Nov 09 20:33:22 GMT+08:00 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_fa
     *
     * @mbg.generated Sat Nov 09 20:33:22 GMT+08:00 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ts_fa
     *
     * @mbg.generated Sat Nov 09 20:33:22 GMT+08:00 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFaNameIsNull() {
            addCriterion("fa_name is null");
            return (Criteria) this;
        }

        public Criteria andFaNameIsNotNull() {
            addCriterion("fa_name is not null");
            return (Criteria) this;
        }

        public Criteria andFaNameEqualTo(String value) {
            addCriterion("fa_name =", value, "faName");
            return (Criteria) this;
        }

        public Criteria andFaNameNotEqualTo(String value) {
            addCriterion("fa_name <>", value, "faName");
            return (Criteria) this;
        }

        public Criteria andFaNameGreaterThan(String value) {
            addCriterion("fa_name >", value, "faName");
            return (Criteria) this;
        }

        public Criteria andFaNameGreaterThanOrEqualTo(String value) {
            addCriterion("fa_name >=", value, "faName");
            return (Criteria) this;
        }

        public Criteria andFaNameLessThan(String value) {
            addCriterion("fa_name <", value, "faName");
            return (Criteria) this;
        }

        public Criteria andFaNameLessThanOrEqualTo(String value) {
            addCriterion("fa_name <=", value, "faName");
            return (Criteria) this;
        }

        public Criteria andFaNameLike(String value) {
            addCriterion("fa_name like", value, "faName");
            return (Criteria) this;
        }

        public Criteria andFaNameNotLike(String value) {
            addCriterion("fa_name not like", value, "faName");
            return (Criteria) this;
        }

        public Criteria andFaNameIn(List<String> values) {
            addCriterion("fa_name in", values, "faName");
            return (Criteria) this;
        }

        public Criteria andFaNameNotIn(List<String> values) {
            addCriterion("fa_name not in", values, "faName");
            return (Criteria) this;
        }

        public Criteria andFaNameBetween(String value1, String value2) {
            addCriterion("fa_name between", value1, value2, "faName");
            return (Criteria) this;
        }

        public Criteria andFaNameNotBetween(String value1, String value2) {
            addCriterion("fa_name not between", value1, value2, "faName");
            return (Criteria) this;
        }

        public Criteria andFaMethodIsNull() {
            addCriterion("fa_method is null");
            return (Criteria) this;
        }

        public Criteria andFaMethodIsNotNull() {
            addCriterion("fa_method is not null");
            return (Criteria) this;
        }

        public Criteria andFaMethodEqualTo(String value) {
            addCriterion("fa_method =", value, "faMethod");
            return (Criteria) this;
        }

        public Criteria andFaMethodNotEqualTo(String value) {
            addCriterion("fa_method <>", value, "faMethod");
            return (Criteria) this;
        }

        public Criteria andFaMethodGreaterThan(String value) {
            addCriterion("fa_method >", value, "faMethod");
            return (Criteria) this;
        }

        public Criteria andFaMethodGreaterThanOrEqualTo(String value) {
            addCriterion("fa_method >=", value, "faMethod");
            return (Criteria) this;
        }

        public Criteria andFaMethodLessThan(String value) {
            addCriterion("fa_method <", value, "faMethod");
            return (Criteria) this;
        }

        public Criteria andFaMethodLessThanOrEqualTo(String value) {
            addCriterion("fa_method <=", value, "faMethod");
            return (Criteria) this;
        }

        public Criteria andFaMethodLike(String value) {
            addCriterion("fa_method like", value, "faMethod");
            return (Criteria) this;
        }

        public Criteria andFaMethodNotLike(String value) {
            addCriterion("fa_method not like", value, "faMethod");
            return (Criteria) this;
        }

        public Criteria andFaMethodIn(List<String> values) {
            addCriterion("fa_method in", values, "faMethod");
            return (Criteria) this;
        }

        public Criteria andFaMethodNotIn(List<String> values) {
            addCriterion("fa_method not in", values, "faMethod");
            return (Criteria) this;
        }

        public Criteria andFaMethodBetween(String value1, String value2) {
            addCriterion("fa_method between", value1, value2, "faMethod");
            return (Criteria) this;
        }

        public Criteria andFaMethodNotBetween(String value1, String value2) {
            addCriterion("fa_method not between", value1, value2, "faMethod");
            return (Criteria) this;
        }

        public Criteria andFaZxwIsNull() {
            addCriterion("fa_zxw is null");
            return (Criteria) this;
        }

        public Criteria andFaZxwIsNotNull() {
            addCriterion("fa_zxw is not null");
            return (Criteria) this;
        }

        public Criteria andFaZxwEqualTo(Integer value) {
            addCriterion("fa_zxw =", value, "faZxw");
            return (Criteria) this;
        }

        public Criteria andFaZxwNotEqualTo(Integer value) {
            addCriterion("fa_zxw <>", value, "faZxw");
            return (Criteria) this;
        }

        public Criteria andFaZxwGreaterThan(Integer value) {
            addCriterion("fa_zxw >", value, "faZxw");
            return (Criteria) this;
        }

        public Criteria andFaZxwGreaterThanOrEqualTo(Integer value) {
            addCriterion("fa_zxw >=", value, "faZxw");
            return (Criteria) this;
        }

        public Criteria andFaZxwLessThan(Integer value) {
            addCriterion("fa_zxw <", value, "faZxw");
            return (Criteria) this;
        }

        public Criteria andFaZxwLessThanOrEqualTo(Integer value) {
            addCriterion("fa_zxw <=", value, "faZxw");
            return (Criteria) this;
        }

        public Criteria andFaZxwIn(List<Integer> values) {
            addCriterion("fa_zxw in", values, "faZxw");
            return (Criteria) this;
        }

        public Criteria andFaZxwNotIn(List<Integer> values) {
            addCriterion("fa_zxw not in", values, "faZxw");
            return (Criteria) this;
        }

        public Criteria andFaZxwBetween(Integer value1, Integer value2) {
            addCriterion("fa_zxw between", value1, value2, "faZxw");
            return (Criteria) this;
        }

        public Criteria andFaZxwNotBetween(Integer value1, Integer value2) {
            addCriterion("fa_zxw not between", value1, value2, "faZxw");
            return (Criteria) this;
        }

        public Criteria andFaCreateIsNull() {
            addCriterion("fa_create is null");
            return (Criteria) this;
        }

        public Criteria andFaCreateIsNotNull() {
            addCriterion("fa_create is not null");
            return (Criteria) this;
        }

        public Criteria andFaCreateEqualTo(Long value) {
            addCriterion("fa_create =", value, "faCreate");
            return (Criteria) this;
        }

        public Criteria andFaCreateNotEqualTo(Long value) {
            addCriterion("fa_create <>", value, "faCreate");
            return (Criteria) this;
        }

        public Criteria andFaCreateGreaterThan(Long value) {
            addCriterion("fa_create >", value, "faCreate");
            return (Criteria) this;
        }

        public Criteria andFaCreateGreaterThanOrEqualTo(Long value) {
            addCriterion("fa_create >=", value, "faCreate");
            return (Criteria) this;
        }

        public Criteria andFaCreateLessThan(Long value) {
            addCriterion("fa_create <", value, "faCreate");
            return (Criteria) this;
        }

        public Criteria andFaCreateLessThanOrEqualTo(Long value) {
            addCriterion("fa_create <=", value, "faCreate");
            return (Criteria) this;
        }

        public Criteria andFaCreateIn(List<Long> values) {
            addCriterion("fa_create in", values, "faCreate");
            return (Criteria) this;
        }

        public Criteria andFaCreateNotIn(List<Long> values) {
            addCriterion("fa_create not in", values, "faCreate");
            return (Criteria) this;
        }

        public Criteria andFaCreateBetween(Long value1, Long value2) {
            addCriterion("fa_create between", value1, value2, "faCreate");
            return (Criteria) this;
        }

        public Criteria andFaCreateNotBetween(Long value1, Long value2) {
            addCriterion("fa_create not between", value1, value2, "faCreate");
            return (Criteria) this;
        }

        public Criteria andFaModifiedIsNull() {
            addCriterion("fa_modified is null");
            return (Criteria) this;
        }

        public Criteria andFaModifiedIsNotNull() {
            addCriterion("fa_modified is not null");
            return (Criteria) this;
        }

        public Criteria andFaModifiedEqualTo(Long value) {
            addCriterion("fa_modified =", value, "faModified");
            return (Criteria) this;
        }

        public Criteria andFaModifiedNotEqualTo(Long value) {
            addCriterion("fa_modified <>", value, "faModified");
            return (Criteria) this;
        }

        public Criteria andFaModifiedGreaterThan(Long value) {
            addCriterion("fa_modified >", value, "faModified");
            return (Criteria) this;
        }

        public Criteria andFaModifiedGreaterThanOrEqualTo(Long value) {
            addCriterion("fa_modified >=", value, "faModified");
            return (Criteria) this;
        }

        public Criteria andFaModifiedLessThan(Long value) {
            addCriterion("fa_modified <", value, "faModified");
            return (Criteria) this;
        }

        public Criteria andFaModifiedLessThanOrEqualTo(Long value) {
            addCriterion("fa_modified <=", value, "faModified");
            return (Criteria) this;
        }

        public Criteria andFaModifiedIn(List<Long> values) {
            addCriterion("fa_modified in", values, "faModified");
            return (Criteria) this;
        }

        public Criteria andFaModifiedNotIn(List<Long> values) {
            addCriterion("fa_modified not in", values, "faModified");
            return (Criteria) this;
        }

        public Criteria andFaModifiedBetween(Long value1, Long value2) {
            addCriterion("fa_modified between", value1, value2, "faModified");
            return (Criteria) this;
        }

        public Criteria andFaModifiedNotBetween(Long value1, Long value2) {
            addCriterion("fa_modified not between", value1, value2, "faModified");
            return (Criteria) this;
        }

        public Criteria andFaXwcIsNull() {
            addCriterion("fa_xwc is null");
            return (Criteria) this;
        }

        public Criteria andFaXwcIsNotNull() {
            addCriterion("fa_xwc is not null");
            return (Criteria) this;
        }

        public Criteria andFaXwcEqualTo(Integer value) {
            addCriterion("fa_xwc =", value, "faXwc");
            return (Criteria) this;
        }

        public Criteria andFaXwcNotEqualTo(Integer value) {
            addCriterion("fa_xwc <>", value, "faXwc");
            return (Criteria) this;
        }

        public Criteria andFaXwcGreaterThan(Integer value) {
            addCriterion("fa_xwc >", value, "faXwc");
            return (Criteria) this;
        }

        public Criteria andFaXwcGreaterThanOrEqualTo(Integer value) {
            addCriterion("fa_xwc >=", value, "faXwc");
            return (Criteria) this;
        }

        public Criteria andFaXwcLessThan(Integer value) {
            addCriterion("fa_xwc <", value, "faXwc");
            return (Criteria) this;
        }

        public Criteria andFaXwcLessThanOrEqualTo(Integer value) {
            addCriterion("fa_xwc <=", value, "faXwc");
            return (Criteria) this;
        }

        public Criteria andFaXwcIn(List<Integer> values) {
            addCriterion("fa_xwc in", values, "faXwc");
            return (Criteria) this;
        }

        public Criteria andFaXwcNotIn(List<Integer> values) {
            addCriterion("fa_xwc not in", values, "faXwc");
            return (Criteria) this;
        }

        public Criteria andFaXwcBetween(Integer value1, Integer value2) {
            addCriterion("fa_xwc between", value1, value2, "faXwc");
            return (Criteria) this;
        }

        public Criteria andFaXwcNotBetween(Integer value1, Integer value2) {
            addCriterion("fa_xwc not between", value1, value2, "faXwc");
            return (Criteria) this;
        }

        public Criteria andFaZqcdIsNull() {
            addCriterion("fa_zqcd is null");
            return (Criteria) this;
        }

        public Criteria andFaZqcdIsNotNull() {
            addCriterion("fa_zqcd is not null");
            return (Criteria) this;
        }

        public Criteria andFaZqcdEqualTo(Integer value) {
            addCriterion("fa_zqcd =", value, "faZqcd");
            return (Criteria) this;
        }

        public Criteria andFaZqcdNotEqualTo(Integer value) {
            addCriterion("fa_zqcd <>", value, "faZqcd");
            return (Criteria) this;
        }

        public Criteria andFaZqcdGreaterThan(Integer value) {
            addCriterion("fa_zqcd >", value, "faZqcd");
            return (Criteria) this;
        }

        public Criteria andFaZqcdGreaterThanOrEqualTo(Integer value) {
            addCriterion("fa_zqcd >=", value, "faZqcd");
            return (Criteria) this;
        }

        public Criteria andFaZqcdLessThan(Integer value) {
            addCriterion("fa_zqcd <", value, "faZqcd");
            return (Criteria) this;
        }

        public Criteria andFaZqcdLessThanOrEqualTo(Integer value) {
            addCriterion("fa_zqcd <=", value, "faZqcd");
            return (Criteria) this;
        }

        public Criteria andFaZqcdIn(List<Integer> values) {
            addCriterion("fa_zqcd in", values, "faZqcd");
            return (Criteria) this;
        }

        public Criteria andFaZqcdNotIn(List<Integer> values) {
            addCriterion("fa_zqcd not in", values, "faZqcd");
            return (Criteria) this;
        }

        public Criteria andFaZqcdBetween(Integer value1, Integer value2) {
            addCriterion("fa_zqcd between", value1, value2, "faZqcd");
            return (Criteria) this;
        }

        public Criteria andFaZqcdNotBetween(Integer value1, Integer value2) {
            addCriterion("fa_zqcd not between", value1, value2, "faZqcd");
            return (Criteria) this;
        }

        public Criteria andFaZxwNameIsNull() {
            addCriterion("fa_zxw_name is null");
            return (Criteria) this;
        }

        public Criteria andFaZxwNameIsNotNull() {
            addCriterion("fa_zxw_name is not null");
            return (Criteria) this;
        }

        public Criteria andFaZxwNameEqualTo(String value) {
            addCriterion("fa_zxw_name =", value, "faZxwName");
            return (Criteria) this;
        }

        public Criteria andFaZxwNameNotEqualTo(String value) {
            addCriterion("fa_zxw_name <>", value, "faZxwName");
            return (Criteria) this;
        }

        public Criteria andFaZxwNameGreaterThan(String value) {
            addCriterion("fa_zxw_name >", value, "faZxwName");
            return (Criteria) this;
        }

        public Criteria andFaZxwNameGreaterThanOrEqualTo(String value) {
            addCriterion("fa_zxw_name >=", value, "faZxwName");
            return (Criteria) this;
        }

        public Criteria andFaZxwNameLessThan(String value) {
            addCriterion("fa_zxw_name <", value, "faZxwName");
            return (Criteria) this;
        }

        public Criteria andFaZxwNameLessThanOrEqualTo(String value) {
            addCriterion("fa_zxw_name <=", value, "faZxwName");
            return (Criteria) this;
        }

        public Criteria andFaZxwNameLike(String value) {
            addCriterion("fa_zxw_name like", value, "faZxwName");
            return (Criteria) this;
        }

        public Criteria andFaZxwNameNotLike(String value) {
            addCriterion("fa_zxw_name not like", value, "faZxwName");
            return (Criteria) this;
        }

        public Criteria andFaZxwNameIn(List<String> values) {
            addCriterion("fa_zxw_name in", values, "faZxwName");
            return (Criteria) this;
        }

        public Criteria andFaZxwNameNotIn(List<String> values) {
            addCriterion("fa_zxw_name not in", values, "faZxwName");
            return (Criteria) this;
        }

        public Criteria andFaZxwNameBetween(String value1, String value2) {
            addCriterion("fa_zxw_name between", value1, value2, "faZxwName");
            return (Criteria) this;
        }

        public Criteria andFaZxwNameNotBetween(String value1, String value2) {
            addCriterion("fa_zxw_name not between", value1, value2, "faZxwName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ts_fa
     *
     * @mbg.generated do_not_delete_during_merge Sat Nov 09 20:33:22 GMT+08:00 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ts_fa
     *
     * @mbg.generated Sat Nov 09 20:33:22 GMT+08:00 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}