package com.jupiter.ts.model;

public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_fa.id
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_fa.fa_name
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    private String faName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_fa.fa_method
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    private String faMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_fa.fa_zxw
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    private String faZxw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_fa.fa_create
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    private Long faCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_fa.fa_modified
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    private Long faModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_fa.id
     *
     * @return the value of ts_fa.id
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_fa.id
     *
     * @param id the value for ts_fa.id
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_fa.fa_name
     *
     * @return the value of ts_fa.fa_name
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public String getFaName() {
        return faName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_fa.fa_name
     *
     * @param faName the value for ts_fa.fa_name
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void setFaName(String faName) {
        this.faName = faName == null ? null : faName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_fa.fa_method
     *
     * @return the value of ts_fa.fa_method
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public String getFaMethod() {
        return faMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_fa.fa_method
     *
     * @param faMethod the value for ts_fa.fa_method
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void setFaMethod(String faMethod) {
        this.faMethod = faMethod == null ? null : faMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_fa.fa_zxw
     *
     * @return the value of ts_fa.fa_zxw
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public String getFaZxw() {
        return faZxw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_fa.fa_zxw
     *
     * @param faZxw the value for ts_fa.fa_zxw
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void setFaZxw(String faZxw) {
        this.faZxw = faZxw == null ? null : faZxw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_fa.fa_create
     *
     * @return the value of ts_fa.fa_create
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public Long getFaCreate() {
        return faCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_fa.fa_create
     *
     * @param faCreate the value for ts_fa.fa_create
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void setFaCreate(Long faCreate) {
        this.faCreate = faCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_fa.fa_modified
     *
     * @return the value of ts_fa.fa_modified
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public Long getFaModified() {
        return faModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_fa.fa_modified
     *
     * @param faModified the value for ts_fa.fa_modified
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void setFaModified(Long faModified) {
        this.faModified = faModified;
    }
}