package com.jupiter.ts.model;

public class Road {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_dl.id
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_dl.dl_name
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    private String dlName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_dl.dl_dd_id
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    private Integer dlDdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_dl.dl_resp
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    private String dlResp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_dl.dl_resp_phone
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    private String dlRespPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_dl.dl_desc
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    private String dlDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_dl.dl_create
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    private Long dlCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_dl.dl_modified
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    private Long dlModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_dl.id
     *
     * @return the value of ts_dl.id
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_dl.id
     *
     * @param id the value for ts_dl.id
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_dl.dl_name
     *
     * @return the value of ts_dl.dl_name
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public String getDlName() {
        return dlName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_dl.dl_name
     *
     * @param dlName the value for ts_dl.dl_name
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void setDlName(String dlName) {
        this.dlName = dlName == null ? null : dlName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_dl.dl_dd_id
     *
     * @return the value of ts_dl.dl_dd_id
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public Integer getDlDdId() {
        return dlDdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_dl.dl_dd_id
     *
     * @param dlDdId the value for ts_dl.dl_dd_id
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void setDlDdId(Integer dlDdId) {
        this.dlDdId = dlDdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_dl.dl_resp
     *
     * @return the value of ts_dl.dl_resp
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public String getDlResp() {
        return dlResp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_dl.dl_resp
     *
     * @param dlResp the value for ts_dl.dl_resp
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void setDlResp(String dlResp) {
        this.dlResp = dlResp == null ? null : dlResp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_dl.dl_resp_phone
     *
     * @return the value of ts_dl.dl_resp_phone
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public String getDlRespPhone() {
        return dlRespPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_dl.dl_resp_phone
     *
     * @param dlRespPhone the value for ts_dl.dl_resp_phone
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void setDlRespPhone(String dlRespPhone) {
        this.dlRespPhone = dlRespPhone == null ? null : dlRespPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_dl.dl_desc
     *
     * @return the value of ts_dl.dl_desc
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public String getDlDesc() {
        return dlDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_dl.dl_desc
     *
     * @param dlDesc the value for ts_dl.dl_desc
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void setDlDesc(String dlDesc) {
        this.dlDesc = dlDesc == null ? null : dlDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_dl.dl_create
     *
     * @return the value of ts_dl.dl_create
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public Long getDlCreate() {
        return dlCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_dl.dl_create
     *
     * @param dlCreate the value for ts_dl.dl_create
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void setDlCreate(Long dlCreate) {
        this.dlCreate = dlCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_dl.dl_modified
     *
     * @return the value of ts_dl.dl_modified
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public Long getDlModified() {
        return dlModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_dl.dl_modified
     *
     * @param dlModified the value for ts_dl.dl_modified
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void setDlModified(Long dlModified) {
        this.dlModified = dlModified;
    }
}