package com.jupiter.ts.model;

import java.util.ArrayList;
import java.util.List;

public class RoadExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public RoadExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDlNameIsNull() {
            addCriterion("dl_name is null");
            return (Criteria) this;
        }

        public Criteria andDlNameIsNotNull() {
            addCriterion("dl_name is not null");
            return (Criteria) this;
        }

        public Criteria andDlNameEqualTo(String value) {
            addCriterion("dl_name =", value, "dlName");
            return (Criteria) this;
        }

        public Criteria andDlNameNotEqualTo(String value) {
            addCriterion("dl_name <>", value, "dlName");
            return (Criteria) this;
        }

        public Criteria andDlNameGreaterThan(String value) {
            addCriterion("dl_name >", value, "dlName");
            return (Criteria) this;
        }

        public Criteria andDlNameGreaterThanOrEqualTo(String value) {
            addCriterion("dl_name >=", value, "dlName");
            return (Criteria) this;
        }

        public Criteria andDlNameLessThan(String value) {
            addCriterion("dl_name <", value, "dlName");
            return (Criteria) this;
        }

        public Criteria andDlNameLessThanOrEqualTo(String value) {
            addCriterion("dl_name <=", value, "dlName");
            return (Criteria) this;
        }

        public Criteria andDlNameLike(String value) {
            addCriterion("dl_name like", value, "dlName");
            return (Criteria) this;
        }

        public Criteria andDlNameNotLike(String value) {
            addCriterion("dl_name not like", value, "dlName");
            return (Criteria) this;
        }

        public Criteria andDlNameIn(List<String> values) {
            addCriterion("dl_name in", values, "dlName");
            return (Criteria) this;
        }

        public Criteria andDlNameNotIn(List<String> values) {
            addCriterion("dl_name not in", values, "dlName");
            return (Criteria) this;
        }

        public Criteria andDlNameBetween(String value1, String value2) {
            addCriterion("dl_name between", value1, value2, "dlName");
            return (Criteria) this;
        }

        public Criteria andDlNameNotBetween(String value1, String value2) {
            addCriterion("dl_name not between", value1, value2, "dlName");
            return (Criteria) this;
        }

        public Criteria andDlDdIdIsNull() {
            addCriterion("dl_dd_id is null");
            return (Criteria) this;
        }

        public Criteria andDlDdIdIsNotNull() {
            addCriterion("dl_dd_id is not null");
            return (Criteria) this;
        }

        public Criteria andDlDdIdEqualTo(Integer value) {
            addCriterion("dl_dd_id =", value, "dlDdId");
            return (Criteria) this;
        }

        public Criteria andDlDdIdNotEqualTo(Integer value) {
            addCriterion("dl_dd_id <>", value, "dlDdId");
            return (Criteria) this;
        }

        public Criteria andDlDdIdGreaterThan(Integer value) {
            addCriterion("dl_dd_id >", value, "dlDdId");
            return (Criteria) this;
        }

        public Criteria andDlDdIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("dl_dd_id >=", value, "dlDdId");
            return (Criteria) this;
        }

        public Criteria andDlDdIdLessThan(Integer value) {
            addCriterion("dl_dd_id <", value, "dlDdId");
            return (Criteria) this;
        }

        public Criteria andDlDdIdLessThanOrEqualTo(Integer value) {
            addCriterion("dl_dd_id <=", value, "dlDdId");
            return (Criteria) this;
        }

        public Criteria andDlDdIdIn(List<Integer> values) {
            addCriterion("dl_dd_id in", values, "dlDdId");
            return (Criteria) this;
        }

        public Criteria andDlDdIdNotIn(List<Integer> values) {
            addCriterion("dl_dd_id not in", values, "dlDdId");
            return (Criteria) this;
        }

        public Criteria andDlDdIdBetween(Integer value1, Integer value2) {
            addCriterion("dl_dd_id between", value1, value2, "dlDdId");
            return (Criteria) this;
        }

        public Criteria andDlDdIdNotBetween(Integer value1, Integer value2) {
            addCriterion("dl_dd_id not between", value1, value2, "dlDdId");
            return (Criteria) this;
        }

        public Criteria andDlRespIsNull() {
            addCriterion("dl_resp is null");
            return (Criteria) this;
        }

        public Criteria andDlRespIsNotNull() {
            addCriterion("dl_resp is not null");
            return (Criteria) this;
        }

        public Criteria andDlRespEqualTo(String value) {
            addCriterion("dl_resp =", value, "dlResp");
            return (Criteria) this;
        }

        public Criteria andDlRespNotEqualTo(String value) {
            addCriterion("dl_resp <>", value, "dlResp");
            return (Criteria) this;
        }

        public Criteria andDlRespGreaterThan(String value) {
            addCriterion("dl_resp >", value, "dlResp");
            return (Criteria) this;
        }

        public Criteria andDlRespGreaterThanOrEqualTo(String value) {
            addCriterion("dl_resp >=", value, "dlResp");
            return (Criteria) this;
        }

        public Criteria andDlRespLessThan(String value) {
            addCriterion("dl_resp <", value, "dlResp");
            return (Criteria) this;
        }

        public Criteria andDlRespLessThanOrEqualTo(String value) {
            addCriterion("dl_resp <=", value, "dlResp");
            return (Criteria) this;
        }

        public Criteria andDlRespLike(String value) {
            addCriterion("dl_resp like", value, "dlResp");
            return (Criteria) this;
        }

        public Criteria andDlRespNotLike(String value) {
            addCriterion("dl_resp not like", value, "dlResp");
            return (Criteria) this;
        }

        public Criteria andDlRespIn(List<String> values) {
            addCriterion("dl_resp in", values, "dlResp");
            return (Criteria) this;
        }

        public Criteria andDlRespNotIn(List<String> values) {
            addCriterion("dl_resp not in", values, "dlResp");
            return (Criteria) this;
        }

        public Criteria andDlRespBetween(String value1, String value2) {
            addCriterion("dl_resp between", value1, value2, "dlResp");
            return (Criteria) this;
        }

        public Criteria andDlRespNotBetween(String value1, String value2) {
            addCriterion("dl_resp not between", value1, value2, "dlResp");
            return (Criteria) this;
        }

        public Criteria andDlRespPhoneIsNull() {
            addCriterion("dl_resp_phone is null");
            return (Criteria) this;
        }

        public Criteria andDlRespPhoneIsNotNull() {
            addCriterion("dl_resp_phone is not null");
            return (Criteria) this;
        }

        public Criteria andDlRespPhoneEqualTo(String value) {
            addCriterion("dl_resp_phone =", value, "dlRespPhone");
            return (Criteria) this;
        }

        public Criteria andDlRespPhoneNotEqualTo(String value) {
            addCriterion("dl_resp_phone <>", value, "dlRespPhone");
            return (Criteria) this;
        }

        public Criteria andDlRespPhoneGreaterThan(String value) {
            addCriterion("dl_resp_phone >", value, "dlRespPhone");
            return (Criteria) this;
        }

        public Criteria andDlRespPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("dl_resp_phone >=", value, "dlRespPhone");
            return (Criteria) this;
        }

        public Criteria andDlRespPhoneLessThan(String value) {
            addCriterion("dl_resp_phone <", value, "dlRespPhone");
            return (Criteria) this;
        }

        public Criteria andDlRespPhoneLessThanOrEqualTo(String value) {
            addCriterion("dl_resp_phone <=", value, "dlRespPhone");
            return (Criteria) this;
        }

        public Criteria andDlRespPhoneLike(String value) {
            addCriterion("dl_resp_phone like", value, "dlRespPhone");
            return (Criteria) this;
        }

        public Criteria andDlRespPhoneNotLike(String value) {
            addCriterion("dl_resp_phone not like", value, "dlRespPhone");
            return (Criteria) this;
        }

        public Criteria andDlRespPhoneIn(List<String> values) {
            addCriterion("dl_resp_phone in", values, "dlRespPhone");
            return (Criteria) this;
        }

        public Criteria andDlRespPhoneNotIn(List<String> values) {
            addCriterion("dl_resp_phone not in", values, "dlRespPhone");
            return (Criteria) this;
        }

        public Criteria andDlRespPhoneBetween(String value1, String value2) {
            addCriterion("dl_resp_phone between", value1, value2, "dlRespPhone");
            return (Criteria) this;
        }

        public Criteria andDlRespPhoneNotBetween(String value1, String value2) {
            addCriterion("dl_resp_phone not between", value1, value2, "dlRespPhone");
            return (Criteria) this;
        }

        public Criteria andDlDescIsNull() {
            addCriterion("dl_desc is null");
            return (Criteria) this;
        }

        public Criteria andDlDescIsNotNull() {
            addCriterion("dl_desc is not null");
            return (Criteria) this;
        }

        public Criteria andDlDescEqualTo(String value) {
            addCriterion("dl_desc =", value, "dlDesc");
            return (Criteria) this;
        }

        public Criteria andDlDescNotEqualTo(String value) {
            addCriterion("dl_desc <>", value, "dlDesc");
            return (Criteria) this;
        }

        public Criteria andDlDescGreaterThan(String value) {
            addCriterion("dl_desc >", value, "dlDesc");
            return (Criteria) this;
        }

        public Criteria andDlDescGreaterThanOrEqualTo(String value) {
            addCriterion("dl_desc >=", value, "dlDesc");
            return (Criteria) this;
        }

        public Criteria andDlDescLessThan(String value) {
            addCriterion("dl_desc <", value, "dlDesc");
            return (Criteria) this;
        }

        public Criteria andDlDescLessThanOrEqualTo(String value) {
            addCriterion("dl_desc <=", value, "dlDesc");
            return (Criteria) this;
        }

        public Criteria andDlDescLike(String value) {
            addCriterion("dl_desc like", value, "dlDesc");
            return (Criteria) this;
        }

        public Criteria andDlDescNotLike(String value) {
            addCriterion("dl_desc not like", value, "dlDesc");
            return (Criteria) this;
        }

        public Criteria andDlDescIn(List<String> values) {
            addCriterion("dl_desc in", values, "dlDesc");
            return (Criteria) this;
        }

        public Criteria andDlDescNotIn(List<String> values) {
            addCriterion("dl_desc not in", values, "dlDesc");
            return (Criteria) this;
        }

        public Criteria andDlDescBetween(String value1, String value2) {
            addCriterion("dl_desc between", value1, value2, "dlDesc");
            return (Criteria) this;
        }

        public Criteria andDlDescNotBetween(String value1, String value2) {
            addCriterion("dl_desc not between", value1, value2, "dlDesc");
            return (Criteria) this;
        }

        public Criteria andDlCreateIsNull() {
            addCriterion("dl_create is null");
            return (Criteria) this;
        }

        public Criteria andDlCreateIsNotNull() {
            addCriterion("dl_create is not null");
            return (Criteria) this;
        }

        public Criteria andDlCreateEqualTo(Long value) {
            addCriterion("dl_create =", value, "dlCreate");
            return (Criteria) this;
        }

        public Criteria andDlCreateNotEqualTo(Long value) {
            addCriterion("dl_create <>", value, "dlCreate");
            return (Criteria) this;
        }

        public Criteria andDlCreateGreaterThan(Long value) {
            addCriterion("dl_create >", value, "dlCreate");
            return (Criteria) this;
        }

        public Criteria andDlCreateGreaterThanOrEqualTo(Long value) {
            addCriterion("dl_create >=", value, "dlCreate");
            return (Criteria) this;
        }

        public Criteria andDlCreateLessThan(Long value) {
            addCriterion("dl_create <", value, "dlCreate");
            return (Criteria) this;
        }

        public Criteria andDlCreateLessThanOrEqualTo(Long value) {
            addCriterion("dl_create <=", value, "dlCreate");
            return (Criteria) this;
        }

        public Criteria andDlCreateIn(List<Long> values) {
            addCriterion("dl_create in", values, "dlCreate");
            return (Criteria) this;
        }

        public Criteria andDlCreateNotIn(List<Long> values) {
            addCriterion("dl_create not in", values, "dlCreate");
            return (Criteria) this;
        }

        public Criteria andDlCreateBetween(Long value1, Long value2) {
            addCriterion("dl_create between", value1, value2, "dlCreate");
            return (Criteria) this;
        }

        public Criteria andDlCreateNotBetween(Long value1, Long value2) {
            addCriterion("dl_create not between", value1, value2, "dlCreate");
            return (Criteria) this;
        }

        public Criteria andDlModifiedIsNull() {
            addCriterion("dl_modified is null");
            return (Criteria) this;
        }

        public Criteria andDlModifiedIsNotNull() {
            addCriterion("dl_modified is not null");
            return (Criteria) this;
        }

        public Criteria andDlModifiedEqualTo(Long value) {
            addCriterion("dl_modified =", value, "dlModified");
            return (Criteria) this;
        }

        public Criteria andDlModifiedNotEqualTo(Long value) {
            addCriterion("dl_modified <>", value, "dlModified");
            return (Criteria) this;
        }

        public Criteria andDlModifiedGreaterThan(Long value) {
            addCriterion("dl_modified >", value, "dlModified");
            return (Criteria) this;
        }

        public Criteria andDlModifiedGreaterThanOrEqualTo(Long value) {
            addCriterion("dl_modified >=", value, "dlModified");
            return (Criteria) this;
        }

        public Criteria andDlModifiedLessThan(Long value) {
            addCriterion("dl_modified <", value, "dlModified");
            return (Criteria) this;
        }

        public Criteria andDlModifiedLessThanOrEqualTo(Long value) {
            addCriterion("dl_modified <=", value, "dlModified");
            return (Criteria) this;
        }

        public Criteria andDlModifiedIn(List<Long> values) {
            addCriterion("dl_modified in", values, "dlModified");
            return (Criteria) this;
        }

        public Criteria andDlModifiedNotIn(List<Long> values) {
            addCriterion("dl_modified not in", values, "dlModified");
            return (Criteria) this;
        }

        public Criteria andDlModifiedBetween(Long value1, Long value2) {
            addCriterion("dl_modified between", value1, value2, "dlModified");
            return (Criteria) this;
        }

        public Criteria andDlModifiedNotBetween(Long value1, Long value2) {
            addCriterion("dl_modified not between", value1, value2, "dlModified");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ts_dl
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}