package com.jupiter.ts.mapper;

import com.jupiter.ts.model.Brigade;
import com.jupiter.ts.model.BrigadeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Component;

@Component
public interface BrigadeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dd
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    long countByExample(BrigadeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dd
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    int deleteByExample(BrigadeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dd
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dd
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    int insert(Brigade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dd
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    int insertSelective(Brigade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dd
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    List<Brigade> selectByExampleWithRowbounds(BrigadeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dd
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    List<Brigade> selectByExample(BrigadeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dd
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    Brigade selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dd
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Brigade record, @Param("example") BrigadeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dd
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Brigade record, @Param("example") BrigadeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dd
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Brigade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dd
     *
     * @mbg.generated Sat Nov 09 16:43:33 GMT+08:00 2019
     */
    int updateByPrimaryKey(Brigade record);
}