package com.jupiter.ts.mapper;

import com.jupiter.ts.model.Interval;
import com.jupiter.ts.model.IntervalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Component;

@Component("intervalMapper")
public interface IntervalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_sd
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    long countByExample(IntervalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_sd
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    int deleteByExample(IntervalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_sd
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_sd
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    int insert(Interval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_sd
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    int insertSelective(Interval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_sd
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    List<Interval> selectByExampleWithRowbounds(IntervalExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_sd
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    List<Interval> selectByExample(IntervalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_sd
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    Interval selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_sd
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Interval record, @Param("example") IntervalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_sd
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Interval record, @Param("example") IntervalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_sd
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Interval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_sd
     *
     * @mbg.generated Wed Oct 30 15:28:56 GMT+08:00 2019
     */
    int updateByPrimaryKey(Interval record);
}