package com.jupiter.ts.mapper;

import com.jupiter.ts.model.Project;
import com.jupiter.ts.model.ProjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Component;

@Component("projectMapper")
public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_fa
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    long countByExample(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_fa
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    int deleteByExample(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_fa
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_fa
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_fa
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    int insertSelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_fa
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    List<Project> selectByExampleWithRowbounds(ProjectExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_fa
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    List<Project> selectByExample(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_fa
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    Project selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_fa
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Project record, @Param("example") ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_fa
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Project record, @Param("example") ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_fa
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_fa
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    int updateByPrimaryKey(Project record);
}