package com.jupiter.ts.mapper;

import com.jupiter.ts.model.Road;
import com.jupiter.ts.model.RoadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Component;

@Component("roadMapper")
public interface RoadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    long countByExample(RoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    int deleteByExample(RoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    int insert(Road record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    int insertSelective(Road record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    List<Road> selectByExampleWithRowbounds(RoadExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    List<Road> selectByExample(RoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    Road selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Road record, @Param("example") RoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Road record, @Param("example") RoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Road record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dl
     *
     * @mbg.generated Thu Nov 07 11:51:39 GMT+08:00 2019
     */
    int updateByPrimaryKey(Road record);
}